//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.13 at 01:16:38 PM CET 
//


package com.reportingtool.xml.dmo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Cabecera de Operacion para operaciones S1
 * 
 * <p>Java class for CABECERAOP_S1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CABECERAOP_S1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumOperacion">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;totalDigits value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TipoOperacion">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;totalDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Caracteristicas">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Caracteristica" maxOccurs="unbounded">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.sepblac.es/DMO}CARACTERISTICAS_ENUM">
 *                         &lt;totalDigits value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="FechaOperacion" type="{http://www.sepblac.es/DMO}FECHA_GEN"/>
 *         &lt;element name="HoraOperacion" type="{http://www.sepblac.es/DMO}HORA" minOccurs="0"/>
 *         &lt;element name="Importe">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="16"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Divisa" type="{http://www.sepblac.es/DMO}DIVISA_ENUM"/>
 *         &lt;element name="ImporteEnEuros">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="16"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PaisOrigen" type="{http://www.sepblac.es/DMO}PAIS_ENUM"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="ProvinciaOrigen" type="{http://www.sepblac.es/DMO}PROV_ENUM"/>
 *           &lt;element name="ProvinciaOrigenEx">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                 &lt;minLength value="1"/>
 *                 &lt;maxLength value="80"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element name="MunicipioOrigen" type="{http://www.sepblac.es/DMO}MUN_ENUM"/>
 *           &lt;element name="MunicipioOrigenEx">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                 &lt;minLength value="1"/>
 *                 &lt;maxLength value="80"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="Oficina">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="4"/>
 *               &lt;pattern value="[0-9][0-9][0-9][0-9]"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NumeroCuenta" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="20"/>
 *               &lt;pattern value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CODIGOS1" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *               &lt;minLength value="25"/>
 *               &lt;pattern value="[0][0][0][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z]"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CABECERAOP_S1", propOrder = {
    "numOperacion",
    "tipoOperacion",
    "caracteristicas",
    "fechaOperacion",
    "horaOperacion",
    "importe",
    "divisa",
    "importeEnEuros",
    "paisOrigen",
    "provinciaOrigen",
    "provinciaOrigenEx",
    "municipioOrigen",
    "municipioOrigenEx",
    "oficina",
    "numeroCuenta",
    "codigos1"
})
public class CABECERAOPS1 {

    @XmlElement(name = "NumOperacion")
    protected int numOperacion;
    @XmlElement(name = "TipoOperacion")
    protected int tipoOperacion;
    @XmlElement(name = "Caracteristicas", required = true)
    protected CABECERAOPS1 .Caracteristicas caracteristicas;
    @XmlElement(name = "FechaOperacion", required = true)
    protected String fechaOperacion;
    @XmlElement(name = "HoraOperacion")
    protected String horaOperacion;
    @XmlElement(name = "Importe", required = true)
    protected BigDecimal importe;
    @XmlElement(name = "Divisa")
    protected int divisa;
    @XmlElement(name = "ImporteEnEuros", required = true)
    protected BigDecimal importeEnEuros;
    @XmlElement(name = "PaisOrigen", required = true)
    protected String paisOrigen;
    @XmlElement(name = "ProvinciaOrigen")
    protected Integer provinciaOrigen;
    @XmlElement(name = "ProvinciaOrigenEx")
    protected String provinciaOrigenEx;
    @XmlElement(name = "MunicipioOrigen")
    protected String municipioOrigen;
    @XmlElement(name = "MunicipioOrigenEx")
    protected String municipioOrigenEx;
    @XmlElement(name = "Oficina", required = true)
    protected String oficina;
    @XmlElement(name = "NumeroCuenta")
    protected String numeroCuenta;
    @XmlElement(name = "CODIGOS1")
    protected String codigos1;

    /**
     * Gets the value of the numOperacion property.
     * 
     */
    public int getNumOperacion() {
        return numOperacion;
    }

    /**
     * Sets the value of the numOperacion property.
     * 
     */
    public void setNumOperacion(int value) {
        this.numOperacion = value;
    }

    /**
     * Gets the value of the tipoOperacion property.
     * 
     */
    public int getTipoOperacion() {
        return tipoOperacion;
    }

    /**
     * Sets the value of the tipoOperacion property.
     * 
     */
    public void setTipoOperacion(int value) {
        this.tipoOperacion = value;
    }

    /**
     * Gets the value of the caracteristicas property.
     * 
     * @return
     *     possible object is
     *     {@link CABECERAOPS1 .Caracteristicas }
     *     
     */
    public CABECERAOPS1 .Caracteristicas getCaracteristicas() {
        return caracteristicas;
    }

    /**
     * Sets the value of the caracteristicas property.
     * 
     * @param value
     *     allowed object is
     *     {@link CABECERAOPS1 .Caracteristicas }
     *     
     */
    public void setCaracteristicas(CABECERAOPS1 .Caracteristicas value) {
        this.caracteristicas = value;
    }

    /**
     * Gets the value of the fechaOperacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaOperacion() {
        return fechaOperacion;
    }

    /**
     * Sets the value of the fechaOperacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaOperacion(String value) {
        this.fechaOperacion = value;
    }

    /**
     * Gets the value of the horaOperacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoraOperacion() {
        return horaOperacion;
    }

    /**
     * Sets the value of the horaOperacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoraOperacion(String value) {
        this.horaOperacion = value;
    }

    /**
     * Gets the value of the importe property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getImporte() {
        return importe;
    }

    /**
     * Sets the value of the importe property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setImporte(BigDecimal value) {
        this.importe = value;
    }

    /**
     * Gets the value of the divisa property.
     * 
     */
    public int getDivisa() {
        return divisa;
    }

    /**
     * Sets the value of the divisa property.
     * 
     */
    public void setDivisa(int value) {
        this.divisa = value;
    }

    /**
     * Gets the value of the importeEnEuros property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getImporteEnEuros() {
        return importeEnEuros;
    }

    /**
     * Sets the value of the importeEnEuros property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setImporteEnEuros(BigDecimal value) {
        this.importeEnEuros = value;
    }

    /**
     * Gets the value of the paisOrigen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaisOrigen() {
        return paisOrigen;
    }

    /**
     * Sets the value of the paisOrigen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaisOrigen(String value) {
        this.paisOrigen = value;
    }

    /**
     * Gets the value of the provinciaOrigen property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProvinciaOrigen() {
        return provinciaOrigen;
    }

    /**
     * Sets the value of the provinciaOrigen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProvinciaOrigen(Integer value) {
        this.provinciaOrigen = value;
    }

    /**
     * Gets the value of the provinciaOrigenEx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvinciaOrigenEx() {
        return provinciaOrigenEx;
    }

    /**
     * Sets the value of the provinciaOrigenEx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvinciaOrigenEx(String value) {
        this.provinciaOrigenEx = value;
    }

    /**
     * Gets the value of the municipioOrigen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMunicipioOrigen() {
        return municipioOrigen;
    }

    /**
     * Sets the value of the municipioOrigen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMunicipioOrigen(String value) {
        this.municipioOrigen = value;
    }

    /**
     * Gets the value of the municipioOrigenEx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMunicipioOrigenEx() {
        return municipioOrigenEx;
    }

    /**
     * Sets the value of the municipioOrigenEx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMunicipioOrigenEx(String value) {
        this.municipioOrigenEx = value;
    }

    /**
     * Gets the value of the oficina property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOficina() {
        return oficina;
    }

    /**
     * Sets the value of the oficina property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOficina(String value) {
        this.oficina = value;
    }

    /**
     * Gets the value of the numeroCuenta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroCuenta() {
        return numeroCuenta;
    }

    /**
     * Sets the value of the numeroCuenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroCuenta(String value) {
        this.numeroCuenta = value;
    }

    /**
     * Gets the value of the codigos1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODIGOS1() {
        return codigos1;
    }

    /**
     * Sets the value of the codigos1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODIGOS1(String value) {
        this.codigos1 = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Caracteristica" maxOccurs="unbounded">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.sepblac.es/DMO}CARACTERISTICAS_ENUM">
     *               &lt;totalDigits value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "caracteristica"
    })
    public static class Caracteristicas {

        @XmlElement(name = "Caracteristica", type = Integer.class)
        protected List<Integer> caracteristica;

        /**
         * Gets the value of the caracteristica property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the caracteristica property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCaracteristica().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getCaracteristica() {
            if (caracteristica == null) {
                caracteristica = new ArrayList<Integer>();
            }
            return this.caracteristica;
        }

    }

}
