//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.13 at 01:16:38 PM CET 
//


package com.reportingtool.xml.dmo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Cabecera de Operacion
 * 
 * <p>Java class for CABECERAOP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CABECERAOP">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumOperacion">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;totalDigits value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TipoOperacion">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;totalDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Caracteristicas">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Caracteristica" maxOccurs="unbounded">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.sepblac.es/DMO}CARACTERISTICAS_ENUM">
 *                         &lt;totalDigits value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="FechaOperacion" type="{http://www.sepblac.es/DMO}FECHA_GEN"/>
 *         &lt;element name="HoraOperacion" type="{http://www.sepblac.es/DMO}HORA" minOccurs="0"/>
 *         &lt;element name="Importe" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="16"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Divisa" type="{http://www.sepblac.es/DMO}DIVISA_ENUM" minOccurs="0"/>
 *         &lt;element name="ImporteEnEuros" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="16"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PaisOrigen" type="{http://www.sepblac.es/DMO}PAIS_ENUM" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="ProvinciaOrigen" type="{http://www.sepblac.es/DMO}PROV_ENUM"/>
 *           &lt;element name="ProvinciaOrigenEx">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                 &lt;minLength value="1"/>
 *                 &lt;maxLength value="80"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="MunicipioOrigen" type="{http://www.sepblac.es/DMO}MUN_ENUM"/>
 *           &lt;element name="MunicipioOrigenEx">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                 &lt;minLength value="1"/>
 *                 &lt;maxLength value="80"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="PaisDestino" type="{http://www.sepblac.es/DMO}PAIS_ENUM" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="ProvinciaDestino" type="{http://www.sepblac.es/DMO}PROV_ENUM"/>
 *           &lt;element name="ProvinciaDestinoEx">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                 &lt;minLength value="1"/>
 *                 &lt;maxLength value="80"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="MunicipioDestino" type="{http://www.sepblac.es/DMO}MUN_ENUM"/>
 *           &lt;element name="MunicipioDestinoEx">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                 &lt;minLength value="1"/>
 *                 &lt;maxLength value="80"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="Oficina" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="4"/>
 *               &lt;pattern value="[0-9][0-9][0-9][0-9]"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NumeroCuenta" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="20"/>
 *               &lt;pattern value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CABECERAOP", propOrder = {
    "numOperacion",
    "tipoOperacion",
    "caracteristicas",
    "fechaOperacion",
    "horaOperacion",
    "importe",
    "divisa",
    "importeEnEuros",
    "paisOrigen",
    "provinciaOrigen",
    "provinciaOrigenEx",
    "municipioOrigen",
    "municipioOrigenEx",
    "paisDestino",
    "provinciaDestino",
    "provinciaDestinoEx",
    "municipioDestino",
    "municipioDestinoEx",
    "oficina",
    "numeroCuenta"
})
public class CABECERAOP {

    @XmlElement(name = "NumOperacion")
    protected int numOperacion;
    @XmlElement(name = "TipoOperacion")
    protected int tipoOperacion;
    @XmlElement(name = "Caracteristicas", required = true)
    protected CABECERAOP.Caracteristicas caracteristicas;
    @XmlElement(name = "FechaOperacion", required = true)
    protected String fechaOperacion;
    @XmlElement(name = "HoraOperacion")
    protected String horaOperacion;
    @XmlElement(name = "Importe")
    protected BigDecimal importe;
    @XmlElement(name = "Divisa")
    protected Integer divisa;
    @XmlElement(name = "ImporteEnEuros")
    protected BigDecimal importeEnEuros;
    @XmlElement(name = "PaisOrigen")
    protected String paisOrigen;
    @XmlElement(name = "ProvinciaOrigen")
    protected Integer provinciaOrigen;
    @XmlElement(name = "ProvinciaOrigenEx")
    protected String provinciaOrigenEx;
    @XmlElement(name = "MunicipioOrigen")
    protected String municipioOrigen;
    @XmlElement(name = "MunicipioOrigenEx")
    protected String municipioOrigenEx;
    @XmlElement(name = "PaisDestino")
    protected String paisDestino;
    @XmlElement(name = "ProvinciaDestino")
    protected Integer provinciaDestino;
    @XmlElement(name = "ProvinciaDestinoEx")
    protected String provinciaDestinoEx;
    @XmlElement(name = "MunicipioDestino")
    protected String municipioDestino;
    @XmlElement(name = "MunicipioDestinoEx")
    protected String municipioDestinoEx;
    @XmlElement(name = "Oficina")
    protected String oficina;
    @XmlElement(name = "NumeroCuenta")
    protected String numeroCuenta;

    /**
     * Gets the value of the numOperacion property.
     * 
     */
    public int getNumOperacion() {
        return numOperacion;
    }

    /**
     * Sets the value of the numOperacion property.
     * 
     */
    public void setNumOperacion(int value) {
        this.numOperacion = value;
    }

    /**
     * Gets the value of the tipoOperacion property.
     * 
     */
    public int getTipoOperacion() {
        return tipoOperacion;
    }

    /**
     * Sets the value of the tipoOperacion property.
     * 
     */
    public void setTipoOperacion(int value) {
        this.tipoOperacion = value;
    }

    /**
     * Gets the value of the caracteristicas property.
     * 
     * @return
     *     possible object is
     *     {@link CABECERAOP.Caracteristicas }
     *     
     */
    public CABECERAOP.Caracteristicas getCaracteristicas() {
        return caracteristicas;
    }

    /**
     * Sets the value of the caracteristicas property.
     * 
     * @param value
     *     allowed object is
     *     {@link CABECERAOP.Caracteristicas }
     *     
     */
    public void setCaracteristicas(CABECERAOP.Caracteristicas value) {
        this.caracteristicas = value;
    }

    /**
     * Gets the value of the fechaOperacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaOperacion() {
        return fechaOperacion;
    }

    /**
     * Sets the value of the fechaOperacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaOperacion(String value) {
        this.fechaOperacion = value;
    }

    /**
     * Gets the value of the horaOperacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoraOperacion() {
        return horaOperacion;
    }

    /**
     * Sets the value of the horaOperacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoraOperacion(String value) {
        this.horaOperacion = value;
    }

    /**
     * Gets the value of the importe property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getImporte() {
        return importe;
    }

    /**
     * Sets the value of the importe property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setImporte(BigDecimal value) {
        this.importe = value;
    }

    /**
     * Gets the value of the divisa property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDivisa() {
        return divisa;
    }

    /**
     * Sets the value of the divisa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDivisa(Integer value) {
        this.divisa = value;
    }

    /**
     * Gets the value of the importeEnEuros property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getImporteEnEuros() {
        return importeEnEuros;
    }

    /**
     * Sets the value of the importeEnEuros property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setImporteEnEuros(BigDecimal value) {
        this.importeEnEuros = value;
    }

    /**
     * Gets the value of the paisOrigen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaisOrigen() {
        return paisOrigen;
    }

    /**
     * Sets the value of the paisOrigen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaisOrigen(String value) {
        this.paisOrigen = value;
    }

    /**
     * Gets the value of the provinciaOrigen property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProvinciaOrigen() {
        return provinciaOrigen;
    }

    /**
     * Sets the value of the provinciaOrigen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProvinciaOrigen(Integer value) {
        this.provinciaOrigen = value;
    }

    /**
     * Gets the value of the provinciaOrigenEx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvinciaOrigenEx() {
        return provinciaOrigenEx;
    }

    /**
     * Sets the value of the provinciaOrigenEx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvinciaOrigenEx(String value) {
        this.provinciaOrigenEx = value;
    }

    /**
     * Gets the value of the municipioOrigen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMunicipioOrigen() {
        return municipioOrigen;
    }

    /**
     * Sets the value of the municipioOrigen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMunicipioOrigen(String value) {
        this.municipioOrigen = value;
    }

    /**
     * Gets the value of the municipioOrigenEx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMunicipioOrigenEx() {
        return municipioOrigenEx;
    }

    /**
     * Sets the value of the municipioOrigenEx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMunicipioOrigenEx(String value) {
        this.municipioOrigenEx = value;
    }

    /**
     * Gets the value of the paisDestino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaisDestino() {
        return paisDestino;
    }

    /**
     * Sets the value of the paisDestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaisDestino(String value) {
        this.paisDestino = value;
    }

    /**
     * Gets the value of the provinciaDestino property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProvinciaDestino() {
        return provinciaDestino;
    }

    /**
     * Sets the value of the provinciaDestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProvinciaDestino(Integer value) {
        this.provinciaDestino = value;
    }

    /**
     * Gets the value of the provinciaDestinoEx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvinciaDestinoEx() {
        return provinciaDestinoEx;
    }

    /**
     * Sets the value of the provinciaDestinoEx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvinciaDestinoEx(String value) {
        this.provinciaDestinoEx = value;
    }

    /**
     * Gets the value of the municipioDestino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMunicipioDestino() {
        return municipioDestino;
    }

    /**
     * Sets the value of the municipioDestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMunicipioDestino(String value) {
        this.municipioDestino = value;
    }

    /**
     * Gets the value of the municipioDestinoEx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMunicipioDestinoEx() {
        return municipioDestinoEx;
    }

    /**
     * Sets the value of the municipioDestinoEx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMunicipioDestinoEx(String value) {
        this.municipioDestinoEx = value;
    }

    /**
     * Gets the value of the oficina property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOficina() {
        return oficina;
    }

    /**
     * Sets the value of the oficina property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOficina(String value) {
        this.oficina = value;
    }

    /**
     * Gets the value of the numeroCuenta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroCuenta() {
        return numeroCuenta;
    }

    /**
     * Sets the value of the numeroCuenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroCuenta(String value) {
        this.numeroCuenta = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Caracteristica" maxOccurs="unbounded">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.sepblac.es/DMO}CARACTERISTICAS_ENUM">
     *               &lt;totalDigits value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "caracteristica"
    })
    public static class Caracteristicas {

        @XmlElement(name = "Caracteristica", type = Integer.class)
        protected List<Integer> caracteristica;

        /**
         * Gets the value of the caracteristica property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the caracteristica property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCaracteristica().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getCaracteristica() {
            if (caracteristica == null) {
                caracteristica = new ArrayList<Integer>();
            }
            return this.caracteristica;
        }

    }

}
