//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.21 at 10:09:42 AM CET 
//


package com.reportingtool.xml.dmo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DatosEntrada">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="NombreEntidad">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="80"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CIFNIFEntidad">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="15"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Representante">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="160"/>
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="FechaDeclaracion" type="{http://www.sepblac.es/DMO}FECHA_GEN"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Periodo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FechaDesde" type="{http://www.sepblac.es/DMO}FECHA_GEN"/>
 *                   &lt;element name="FechaHasta" type="{http://www.sepblac.es/DMO}FECHA_GEN"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Operaciones" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="5"/>
 *             &lt;minLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="TYPE" use="required" type="{http://www.sepblac.es/DMO}TIPODECL_ENUM" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datosEntrada",
    "periodo",
    "operaciones"
})
@XmlRootElement(name = "DeclaracionNegativa")
public class DeclaracionNegativa {

    @XmlElement(name = "DatosEntrada", required = true)
    protected DeclaracionNegativa.DatosEntrada datosEntrada;
    @XmlElement(name = "Periodo", required = true)
    protected DeclaracionNegativa.Periodo periodo;
    @XmlElement(name = "Operaciones", required = true)
    protected Object operaciones;
    @XmlAttribute(name = "ID", required = true)
    protected String id;
    @XmlAttribute(name = "TYPE", required = true)
    protected TIPODECLENUM type;

    /**
     * Gets the value of the datosEntrada property.
     * 
     * @return
     *     possible object is
     *     {@link DeclaracionNegativa.DatosEntrada }
     *     
     */
    public DeclaracionNegativa.DatosEntrada getDatosEntrada() {
        return datosEntrada;
    }

    /**
     * Sets the value of the datosEntrada property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeclaracionNegativa.DatosEntrada }
     *     
     */
    public void setDatosEntrada(DeclaracionNegativa.DatosEntrada value) {
        this.datosEntrada = value;
    }

    /**
     * Gets the value of the periodo property.
     * 
     * @return
     *     possible object is
     *     {@link DeclaracionNegativa.Periodo }
     *     
     */
    public DeclaracionNegativa.Periodo getPeriodo() {
        return periodo;
    }

    /**
     * Sets the value of the periodo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeclaracionNegativa.Periodo }
     *     
     */
    public void setPeriodo(DeclaracionNegativa.Periodo value) {
        this.periodo = value;
    }

    /**
     * Gets the value of the operaciones property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getOperaciones() {
        return operaciones;
    }

    /**
     * Sets the value of the operaciones property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setOperaciones(Object value) {
        this.operaciones = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TIPODECLENUM }
     *     
     */
    public TIPODECLENUM getTYPE() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIPODECLENUM }
     *     
     */
    public void setTYPE(TIPODECLENUM value) {
        this.type = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="NombreEntidad">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="80"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CIFNIFEntidad">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="15"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Representante">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="160"/>
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="FechaDeclaracion" type="{http://www.sepblac.es/DMO}FECHA_GEN"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nombreEntidad",
        "cifnifEntidad",
        "representante",
        "fechaDeclaracion"
    })
    public static class DatosEntrada {

        @XmlElement(name = "NombreEntidad", required = true)
        protected String nombreEntidad;
        @XmlElement(name = "CIFNIFEntidad", required = true)
        protected String cifnifEntidad;
        @XmlElement(name = "Representante", required = true)
        protected String representante;
        @XmlElement(name = "FechaDeclaracion", required = true)
        protected String fechaDeclaracion;

        /**
         * Gets the value of the nombreEntidad property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNombreEntidad() {
            return nombreEntidad;
        }

        /**
         * Sets the value of the nombreEntidad property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNombreEntidad(String value) {
            this.nombreEntidad = value;
        }

        /**
         * Gets the value of the cifnifEntidad property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCIFNIFEntidad() {
            return cifnifEntidad;
        }

        /**
         * Sets the value of the cifnifEntidad property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCIFNIFEntidad(String value) {
            this.cifnifEntidad = value;
        }

        /**
         * Gets the value of the representante property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRepresentante() {
            return representante;
        }

        /**
         * Sets the value of the representante property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRepresentante(String value) {
            this.representante = value;
        }

        /**
         * Gets the value of the fechaDeclaracion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFechaDeclaracion() {
            return fechaDeclaracion;
        }

        /**
         * Sets the value of the fechaDeclaracion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFechaDeclaracion(String value) {
            this.fechaDeclaracion = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FechaDesde" type="{http://www.sepblac.es/DMO}FECHA_GEN"/>
     *         &lt;element name="FechaHasta" type="{http://www.sepblac.es/DMO}FECHA_GEN"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fechaDesde",
        "fechaHasta"
    })
    public static class Periodo {

        @XmlElement(name = "FechaDesde", required = true)
        protected String fechaDesde;
        @XmlElement(name = "FechaHasta", required = true)
        protected String fechaHasta;

        /**
         * Gets the value of the fechaDesde property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFechaDesde() {
            return fechaDesde;
        }

        /**
         * Sets the value of the fechaDesde property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFechaDesde(String value) {
            this.fechaDesde = value;
        }

        /**
         * Gets the value of the fechaHasta property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFechaHasta() {
            return fechaHasta;
        }

        /**
         * Sets the value of the fechaHasta property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFechaHasta(String value) {
            this.fechaHasta = value;
        }

    }

}
