//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.21 at 10:09:42 AM CET 
//


package com.reportingtool.xml.dmo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DatosEntrada">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="NombreEntidad">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="80"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CIFNIFEntidad">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="15"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Representante">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="160"/>
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="MesDeclaracion">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="7"/>
 *                         &lt;maxLength value="7"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="FechaDeclaracion" type="{http://www.sepblac.es/DMO}FECHA_GEN"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Operaciones">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.sepblac.es/DMO}OperacionGeneral" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{http://www.sepblac.es/DMO}Operacion8_20" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="5"/>
 *             &lt;minLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="TYPE" use="required" type="{http://www.sepblac.es/DMO}TIPODECL_ENUM" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datosEntrada",
    "operaciones"
})
@XmlRootElement(name = "DeclaracionPositiva")
public class DeclaracionPositiva {

    @XmlElement(name = "DatosEntrada", required = true)
    protected DeclaracionPositiva.DatosEntrada datosEntrada;
    @XmlElement(name = "Operaciones", required = true)
    protected DeclaracionPositiva.Operaciones operaciones;
    @XmlAttribute(name = "ID", required = true)
    protected String id;
    @XmlAttribute(name = "TYPE", required = true)
    protected TIPODECLENUM type;

    /**
     * Gets the value of the datosEntrada property.
     * 
     * @return
     *     possible object is
     *     {@link DeclaracionPositiva.DatosEntrada }
     *     
     */
    public DeclaracionPositiva.DatosEntrada getDatosEntrada() {
        return datosEntrada;
    }

    /**
     * Sets the value of the datosEntrada property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeclaracionPositiva.DatosEntrada }
     *     
     */
    public void setDatosEntrada(DeclaracionPositiva.DatosEntrada value) {
        this.datosEntrada = value;
    }

    /**
     * Gets the value of the operaciones property.
     * 
     * @return
     *     possible object is
     *     {@link DeclaracionPositiva.Operaciones }
     *     
     */
    public DeclaracionPositiva.Operaciones getOperaciones() {
        return operaciones;
    }

    /**
     * Sets the value of the operaciones property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeclaracionPositiva.Operaciones }
     *     
     */
    public void setOperaciones(DeclaracionPositiva.Operaciones value) {
        this.operaciones = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TIPODECLENUM }
     *     
     */
    public TIPODECLENUM getTYPE() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIPODECLENUM }
     *     
     */
    public void setTYPE(TIPODECLENUM value) {
        this.type = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="NombreEntidad">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="80"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CIFNIFEntidad">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="15"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Representante">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="160"/>
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="MesDeclaracion">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="7"/>
     *               &lt;maxLength value="7"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="FechaDeclaracion" type="{http://www.sepblac.es/DMO}FECHA_GEN"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nombreEntidad",
        "cifnifEntidad",
        "representante",
        "mesDeclaracion",
        "fechaDeclaracion"
    })
    public static class DatosEntrada {

        @XmlElement(name = "NombreEntidad", required = true)
        protected String nombreEntidad;
        @XmlElement(name = "CIFNIFEntidad", required = true)
        protected String cifnifEntidad;
        @XmlElement(name = "Representante", required = true)
        protected String representante;
        @XmlElement(name = "MesDeclaracion", required = true)
        protected String mesDeclaracion;
        @XmlElement(name = "FechaDeclaracion", required = true)
        protected String fechaDeclaracion;

        /**
         * Gets the value of the nombreEntidad property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNombreEntidad() {
            return nombreEntidad;
        }

        /**
         * Sets the value of the nombreEntidad property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNombreEntidad(String value) {
            this.nombreEntidad = value;
        }

        /**
         * Gets the value of the cifnifEntidad property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCIFNIFEntidad() {
            return cifnifEntidad;
        }

        /**
         * Sets the value of the cifnifEntidad property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCIFNIFEntidad(String value) {
            this.cifnifEntidad = value;
        }

        /**
         * Gets the value of the representante property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRepresentante() {
            return representante;
        }

        /**
         * Sets the value of the representante property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRepresentante(String value) {
            this.representante = value;
        }

        /**
         * Gets the value of the mesDeclaracion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMesDeclaracion() {
            return mesDeclaracion;
        }

        /**
         * Sets the value of the mesDeclaracion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMesDeclaracion(String value) {
            this.mesDeclaracion = value;
        }

        /**
         * Gets the value of the fechaDeclaracion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFechaDeclaracion() {
            return fechaDeclaracion;
        }

        /**
         * Sets the value of the fechaDeclaracion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFechaDeclaracion(String value) {
            this.fechaDeclaracion = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.sepblac.es/DMO}OperacionGeneral" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{http://www.sepblac.es/DMO}Operacion8_20" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "operacionGeneral",
        "operacion820"
    })
    public static class Operaciones {

        @XmlElement(name = "OperacionGeneral", namespace = "http://www.sepblac.es/DMO")
        protected List<OperacionGeneral> operacionGeneral;
        @XmlElement(name = "Operacion8_20", namespace = "http://www.sepblac.es/DMO")
        protected List<Operacion820> operacion820;

        /**
         * Gets the value of the operacionGeneral property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the operacionGeneral property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOperacionGeneral().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OperacionGeneral }
         * 
         * 
         */
        public List<OperacionGeneral> getOperacionGeneral() {
            if (operacionGeneral == null) {
                operacionGeneral = new ArrayList<OperacionGeneral>();
            }
            return this.operacionGeneral;
        }

        /**
         * Gets the value of the operacion820 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the operacion820 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOperacion820().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Operacion820 }
         * 
         * 
         */
        public List<Operacion820> getOperacion820() {
            if (operacion820 == null) {
                operacion820 = new ArrayList<Operacion820>();
            }
            return this.operacion820;
        }

    }

}
