//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.21 at 10:09:42 AM CET 
//


package com.reportingtool.xml.dmo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.sepblac.es/DMO}DeclaracionMovimientos"/>
 *         &lt;element ref="{http://www.sepblac.es/DMO}DeclaracionNegativa"/>
 *         &lt;element ref="{http://www.sepblac.es/DMO}DeclaracionPositiva"/>
 *         &lt;element ref="{http://www.sepblac.es/DMO}Fraccionamiento"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "declaracionMovimientos",
    "declaracionNegativa",
    "declaracionPositiva",
    "fraccionamiento"
})
@XmlRootElement(name = "Declaracion")
public class Declaracion {

    @XmlElement(name = "DeclaracionMovimientos", namespace = "http://www.sepblac.es/DMO")
    protected DeclaracionMovimientos declaracionMovimientos;
    @XmlElement(name = "DeclaracionNegativa", namespace = "http://www.sepblac.es/DMO")
    protected DeclaracionNegativa declaracionNegativa;
    @XmlElement(name = "DeclaracionPositiva", namespace = "http://www.sepblac.es/DMO")
    protected DeclaracionPositiva declaracionPositiva;
    @XmlElement(name = "Fraccionamiento", namespace = "http://www.sepblac.es/DMO")
    protected Fraccionamiento fraccionamiento;

    /**
     * Gets the value of the declaracionMovimientos property.
     * 
     * @return
     *     possible object is
     *     {@link DeclaracionMovimientos }
     *     
     */
    public DeclaracionMovimientos getDeclaracionMovimientos() {
        return declaracionMovimientos;
    }

    /**
     * Sets the value of the declaracionMovimientos property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeclaracionMovimientos }
     *     
     */
    public void setDeclaracionMovimientos(DeclaracionMovimientos value) {
        this.declaracionMovimientos = value;
    }

    /**
     * Gets the value of the declaracionNegativa property.
     * 
     * @return
     *     possible object is
     *     {@link DeclaracionNegativa }
     *     
     */
    public DeclaracionNegativa getDeclaracionNegativa() {
        return declaracionNegativa;
    }

    /**
     * Sets the value of the declaracionNegativa property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeclaracionNegativa }
     *     
     */
    public void setDeclaracionNegativa(DeclaracionNegativa value) {
        this.declaracionNegativa = value;
    }

    /**
     * Gets the value of the declaracionPositiva property.
     * 
     * @return
     *     possible object is
     *     {@link DeclaracionPositiva }
     *     
     */
    public DeclaracionPositiva getDeclaracionPositiva() {
        return declaracionPositiva;
    }

    /**
     * Sets the value of the declaracionPositiva property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeclaracionPositiva }
     *     
     */
    public void setDeclaracionPositiva(DeclaracionPositiva value) {
        this.declaracionPositiva = value;
    }

    /**
     * Gets the value of the fraccionamiento property.
     * 
     * @return
     *     possible object is
     *     {@link Fraccionamiento }
     *     
     */
    public Fraccionamiento getFraccionamiento() {
        return fraccionamiento;
    }

    /**
     * Sets the value of the fraccionamiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fraccionamiento }
     *     
     */
    public void setFraccionamiento(Fraccionamiento value) {
        this.fraccionamiento = value;
    }

}
