//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.13 at 01:16:38 PM CET 
//


package com.reportingtool.xml.dmo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Documento identificativo de personas fisicas
 * 
 * <p>Java class for DOCIDENTIF_PF complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DOCIDENTIF_PF">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.sepblac.es/DMO}DOCIDENTIF">
 *       &lt;sequence>
 *         &lt;element name="TipoDocIdentif">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.sepblac.es/DMO}TIPDIPF_ENUM">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DOCIDENTIF_PF", propOrder = {
    "tipoDocIdentif"
})
@XmlSeeAlso({
    com.reportingtool.xml.dmo.PERSONAFIS.DocIdentifsPF.DocIdentifPF.class
})
public class DOCIDENTIFPF
    extends DOCIDENTIF
{

    @XmlElement(name = "TipoDocIdentif")
    protected int tipoDocIdentif;

    /**
     * Gets the value of the tipoDocIdentif property.
     * 
     */
    public int getTipoDocIdentif() {
        return tipoDocIdentif;
    }

    /**
     * Sets the value of the tipoDocIdentif property.
     * 
     */
    public void setTipoDocIdentif(int value) {
        this.tipoDocIdentif = value;
    }

}
