//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.13 at 01:16:38 PM CET 
//


package com.reportingtool.xml.dmo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Clase general de documento identificativo
 * 
 * <p>Java class for DOCIDENTIF complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DOCIDENTIF">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PaisExpedicion" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.sepblac.es/DMO}PAIS_ENUM">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="NumDocIdentif" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="15"/>
 *             &lt;minLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DOCIDENTIF", propOrder = {
    "paisExpedicion"
})
@XmlSeeAlso({
    DOCIDENTIFPJ.class,
    DOCIDENTIFPF.class
})
public class DOCIDENTIF {

    @XmlElement(name = "PaisExpedicion")
    protected String paisExpedicion;
    @XmlAttribute(name = "NumDocIdentif", required = true)
    protected String numDocIdentif;

    /**
     * Gets the value of the paisExpedicion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaisExpedicion() {
        return paisExpedicion;
    }

    /**
     * Sets the value of the paisExpedicion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaisExpedicion(String value) {
        this.paisExpedicion = value;
    }

    /**
     * Gets the value of the numDocIdentif property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumDocIdentif() {
        return numDocIdentif;
    }

    /**
     * Sets the value of the numDocIdentif property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumDocIdentif(String value) {
        this.numDocIdentif = value;
    }

}
