//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.11 at 12:19:27 PM CET 
//


package com.reportingtool.xml.dmo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DatosEntrada">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CIFNIFEntidad">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="15"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="MesDeclaracion">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="7"/>
 *                         &lt;maxLength value="7"/>
 *                         &lt;pattern value="(19[0-9]{2}|20[0-9]{2})/([0][1-9]|[1][0-2])"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Operaciones">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.sepblac.es/DMO}OperacionGeneral" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{http://www.sepblac.es/DMO}Operacion8_20" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datosEntrada",
    "operaciones"
})
@XmlRootElement(name = "FraccionamientoImport")
public class FraccionamientoImport {

    @XmlElement(name = "DatosEntrada", required = true)
    protected FraccionamientoImport.DatosEntrada datosEntrada;
    @XmlElement(name = "Operaciones", required = true)
    protected FraccionamientoImport.Operaciones operaciones;

    /**
     * Gets the value of the datosEntrada property.
     * 
     * @return
     *     possible object is
     *     {@link FraccionamientoImport.DatosEntrada }
     *     
     */
    public FraccionamientoImport.DatosEntrada getDatosEntrada() {
        return datosEntrada;
    }

    /**
     * Sets the value of the datosEntrada property.
     * 
     * @param value
     *     allowed object is
     *     {@link FraccionamientoImport.DatosEntrada }
     *     
     */
    public void setDatosEntrada(FraccionamientoImport.DatosEntrada value) {
        this.datosEntrada = value;
    }

    /**
     * Gets the value of the operaciones property.
     * 
     * @return
     *     possible object is
     *     {@link FraccionamientoImport.Operaciones }
     *     
     */
    public FraccionamientoImport.Operaciones getOperaciones() {
        return operaciones;
    }

    /**
     * Sets the value of the operaciones property.
     * 
     * @param value
     *     allowed object is
     *     {@link FraccionamientoImport.Operaciones }
     *     
     */
    public void setOperaciones(FraccionamientoImport.Operaciones value) {
        this.operaciones = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CIFNIFEntidad">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="15"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="MesDeclaracion">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="7"/>
     *               &lt;maxLength value="7"/>
     *               &lt;pattern value="(19[0-9]{2}|20[0-9]{2})/([0][1-9]|[1][0-2])"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "cifnifEntidad",
        "mesDeclaracion"
    })
    public static class DatosEntrada {

        @XmlElement(name = "ID", required = true)
        protected String id;
        @XmlElement(name = "CIFNIFEntidad", required = true)
        protected String cifnifEntidad;
        @XmlElement(name = "MesDeclaracion", required = true)
        protected String mesDeclaracion;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the cifnifEntidad property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCIFNIFEntidad() {
            return cifnifEntidad;
        }

        /**
         * Sets the value of the cifnifEntidad property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCIFNIFEntidad(String value) {
            this.cifnifEntidad = value;
        }

        /**
         * Gets the value of the mesDeclaracion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMesDeclaracion() {
            return mesDeclaracion;
        }

        /**
         * Sets the value of the mesDeclaracion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMesDeclaracion(String value) {
            this.mesDeclaracion = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.sepblac.es/DMO}OperacionGeneral" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{http://www.sepblac.es/DMO}Operacion8_20" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "operacionGeneral",
        "operacion820"
    })
    public static class Operaciones {

        @XmlElement(name = "OperacionGeneral", namespace = "http://www.sepblac.es/DMO")
        protected List<OperacionGeneral> operacionGeneral;
        @XmlElement(name = "Operacion8_20", namespace = "http://www.sepblac.es/DMO")
        protected List<Operacion820> operacion820;

        /**
         * Gets the value of the operacionGeneral property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the operacionGeneral property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOperacionGeneral().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OperacionGeneral }
         * 
         * 
         */
        public List<OperacionGeneral> getOperacionGeneral() {
            if (operacionGeneral == null) {
                operacionGeneral = new ArrayList<OperacionGeneral>();
            }
            return this.operacionGeneral;
        }

        /**
         * Gets the value of the operacion820 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the operacion820 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOperacion820().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Operacion820 }
         * 
         * 
         */
        public List<Operacion820> getOperacion820() {
            if (operacion820 == null) {
                operacion820 = new ArrayList<Operacion820>();
            }
            return this.operacion820;
        }

    }

}
