//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.11 at 12:19:27 PM CET 
//


package com.reportingtool.xml.dmo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.sepblac.es/DMO}FraccionamientoImport" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fraccionamientoImport"
})
@XmlRootElement(name = "FraccionamientosImport")
public class FraccionamientosImport {

    @XmlElement(name = "FraccionamientoImport", namespace = "http://www.sepblac.es/DMO", required = true)
    protected List<FraccionamientoImport> fraccionamientoImport;

    /**
     * Gets the value of the fraccionamientoImport property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fraccionamientoImport property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFraccionamientoImport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FraccionamientoImport }
     * 
     * 
     */
    public List<FraccionamientoImport> getFraccionamientoImport() {
        if (fraccionamientoImport == null) {
            fraccionamientoImport = new ArrayList<FraccionamientoImport>();
        }
        return this.fraccionamientoImport;
    }

}
