//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.13 at 01:16:38 PM CET 
//


package com.reportingtool.xml.dmo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.reportingtool.xml.dmo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactoryDMO_AEAT {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.reportingtool.xml.dmo
     * 
     */
    public ObjectFactoryDMO_AEAT() {
    }

    /**
     * Create an instance of {@link DOMICILIOS1 }
     * 
     */
    public DOMICILIOS1 createDOMICILIOS1() {
        return new DOMICILIOS1();
    }

    /**
     * Create an instance of {@link PROV51 }
     * 
     */
    public PROV51 createPROV51() {
        return new PROV51();
    }

    /**
     * Create an instance of {@link PROVINCIAS }
     * 
     */
    public PROVINCIAS createPROVINCIAS() {
        return new PROVINCIAS();
    }

    /**
     * Create an instance of {@link PERSONAFIS }
     * 
     */
    public PERSONAFIS createPERSONAFIS() {
        return new PERSONAFIS();
    }

    /**
     * Create an instance of {@link PROV22 }
     * 
     */
    public PROV22 createPROV22() {
        return new PROV22();
    }

    /**
     * Create an instance of {@link DOCIDENTIFPF }
     * 
     */
    public DOCIDENTIFPF createDOCIDENTIFPF() {
        return new DOCIDENTIFPF();
    }

    /**
     * Create an instance of {@link Operacion2325 .Operacion.DiligenciaEntidad }
     * 
     */
    public Operacion2325 .Operacion.DiligenciaEntidad createOperacion2325OperacionDiligenciaEntidad() {
        return new Operacion2325 .Operacion.DiligenciaEntidad();
    }

    /**
     * Create an instance of {@link PROV42 }
     * 
     */
    public PROV42 createPROV42() {
        return new PROV42();
    }

    /**
     * Create an instance of {@link PROV40 }
     * 
     */
    public PROV40 createPROV40() {
        return new PROV40();
    }

    /**
     * Create an instance of {@link PROV31 }
     * 
     */
    public PROV31 createPROV31() {
        return new PROV31();
    }

    /**
     * Create an instance of {@link Operacion2325 .Intervinientes.Propietario.PersonaFisica }
     * 
     */
    public Operacion2325 .Intervinientes.Propietario.PersonaFisica createOperacion2325IntervinientesPropietarioPersonaFisica() {
        return new Operacion2325 .Intervinientes.Propietario.PersonaFisica();
    }

    /**
     * Create an instance of {@link PROV48 }
     * 
     */
    public PROV48 createPROV48() {
        return new PROV48();
    }

    /**
     * Create an instance of {@link PROV44 }
     * 
     */
    public PROV44 createPROV44() {
        return new PROV44();
    }

    /**
     * Create an instance of {@link PROV4 }
     * 
     */
    public PROV4 createPROV4() {
        return new PROV4();
    }

    /**
     * Create an instance of {@link DOMICILIO }
     * 
     */
    public DOMICILIO createDOMICILIO() {
        return new DOMICILIO();
    }

    /**
     * Create an instance of {@link PROV18 }
     * 
     */
    public PROV18 createPROV18() {
        return new PROV18();
    }

    /**
     * Create an instance of {@link PROV34 }
     * 
     */
    public PROV34 createPROV34() {
        return new PROV34();
    }

    /**
     * Create an instance of {@link CABECERAOPS1 }
     * 
     */
    public CABECERAOPS1 createCABECERAOPS1() {
        return new CABECERAOPS1();
    }

    /**
     * Create an instance of {@link PROV25 }
     * 
     */
    public PROV25 createPROV25() {
        return new PROV25();
    }

    /**
     * Create an instance of {@link PERSONAJUR.Telefonos }
     * 
     */
    public PERSONAJUR.Telefonos createPERSONAJURTelefonos() {
        return new PERSONAJUR.Telefonos();
    }

    /**
     * Create an instance of {@link Operacion2325 .Operacion.MediosPago }
     * 
     */
    public Operacion2325 .Operacion.MediosPago createOperacion2325OperacionMediosPago() {
        return new Operacion2325 .Operacion.MediosPago();
    }

    /**
     * Create an instance of {@link PERSONAFIS.Telefonos }
     * 
     */
    public PERSONAFIS.Telefonos createPERSONAFISTelefonos() {
        return new PERSONAFIS.Telefonos();
    }

    /**
     * Create an instance of {@link PROV16 }
     * 
     */
    public PROV16 createPROV16() {
        return new PROV16();
    }

    /**
     * Create an instance of {@link Operacion2325 .Intervinientes.Declarante.PersonaFisica }
     * 
     */
    public Operacion2325 .Intervinientes.Declarante.PersonaFisica createOperacion2325IntervinientesDeclarantePersonaFisica() {
        return new Operacion2325 .Intervinientes.Declarante.PersonaFisica();
    }

    /**
     * Create an instance of {@link Operacion2325 .Operacion.FirmaDeclaracion }
     * 
     */
    public Operacion2325 .Operacion.FirmaDeclaracion createOperacion2325OperacionFirmaDeclaracion() {
        return new Operacion2325 .Operacion.FirmaDeclaracion();
    }

    /**
     * Create an instance of {@link PROV33 }
     * 
     */
    public PROV33 createPROV33() {
        return new PROV33();
    }

    /**
     * Create an instance of {@link PERSONAFIS.DocIdentifsPF }
     * 
     */
    public PERSONAFIS.DocIdentifsPF createPERSONAFISDocIdentifsPF() {
        return new PERSONAFIS.DocIdentifsPF();
    }

    /**
     * Create an instance of {@link PROV41 }
     * 
     */
    public PROV41 createPROV41() {
        return new PROV41();
    }

    /**
     * Create an instance of {@link PROV45 }
     * 
     */
    public PROV45 createPROV45() {
        return new PROV45();
    }

    /**
     * Create an instance of {@link Operacion2325 .Operacion }
     * 
     */
    public Operacion2325 .Operacion createOperacion2325Operacion() {
        return new Operacion2325 .Operacion();
    }

    /**
     * Create an instance of {@link Operacion2325 }
     * 
     */
    public Operacion2325 createOperacion2325() {
        return new Operacion2325();
    }

    /**
     * Create an instance of {@link PERSONAJUR }
     * 
     */
    public PERSONAJUR createPERSONAJUR() {
        return new PERSONAJUR();
    }

    /**
     * Create an instance of {@link PERSONAFIS.DocIdentifsPF.DocIdentifPF }
     * 
     */
    public PERSONAFIS.DocIdentifsPF.DocIdentifPF createPERSONAFISDocIdentifsPFDocIdentifPF() {
        return new PERSONAFIS.DocIdentifsPF.DocIdentifPF();
    }

    /**
     * Create an instance of {@link PROV1 }
     * 
     */
    public PROV1 createPROV1() {
        return new PROV1();
    }

    /**
     * Create an instance of {@link PERSONAJUR.DomiciliosPJ }
     * 
     */
    public PERSONAJUR.DomiciliosPJ createPERSONAJURDomiciliosPJ() {
        return new PERSONAJUR.DomiciliosPJ();
    }

    /**
     * Create an instance of {@link OperacionesAEAT }
     * 
     */
    public OperacionesAEAT createOperacionesAEAT() {
        return new OperacionesAEAT();
    }

    /**
     * Create an instance of {@link PROV21 }
     * 
     */
    public PROV21 createPROV21() {
        return new PROV21();
    }

    /**
     * Create an instance of {@link PERSONAJUR.Telefonos.Telefono }
     * 
     */
    public PERSONAJUR.Telefonos.Telefono createPERSONAJURTelefonosTelefono() {
        return new PERSONAJUR.Telefonos.Telefono();
    }

    /**
     * Create an instance of {@link PROV26 }
     * 
     */
    public PROV26 createPROV26() {
        return new PROV26();
    }

    /**
     * Create an instance of {@link PROV36 }
     * 
     */
    public PROV36 createPROV36() {
        return new PROV36();
    }

    /**
     * Create an instance of {@link PROV19 }
     * 
     */
    public PROV19 createPROV19() {
        return new PROV19();
    }

    /**
     * Create an instance of {@link PROV29 }
     * 
     */
    public PROV29 createPROV29() {
        return new PROV29();
    }

    /**
     * Create an instance of {@link PROV50 }
     * 
     */
    public PROV50 createPROV50() {
        return new PROV50();
    }

    /**
     * Create an instance of {@link PROV39 }
     * 
     */
    public PROV39 createPROV39() {
        return new PROV39();
    }

    /**
     * Create an instance of {@link PROV2 }
     * 
     */
    public PROV2 createPROV2() {
        return new PROV2();
    }

    /**
     * Create an instance of {@link PROV6 }
     * 
     */
    public PROV6 createPROV6() {
        return new PROV6();
    }

    /**
     * Create an instance of {@link PROV47 }
     * 
     */
    public PROV47 createPROV47() {
        return new PROV47();
    }

    /**
     * Create an instance of {@link PROV30 }
     * 
     */
    public PROV30 createPROV30() {
        return new PROV30();
    }

    /**
     * Create an instance of {@link PROV49 }
     * 
     */
    public PROV49 createPROV49() {
        return new PROV49();
    }

    /**
     * Create an instance of {@link Operacion2325 .Intervinientes.Propietario.Sociedad }
     * 
     */
    public Operacion2325 .Intervinientes.Propietario.Sociedad createOperacion2325IntervinientesPropietarioSociedad() {
        return new Operacion2325 .Intervinientes.Propietario.Sociedad();
    }

    /**
     * Create an instance of {@link PERSONAFIS.Telefonos.Telefono }
     * 
     */
    public PERSONAFIS.Telefonos.Telefono createPERSONAFISTelefonosTelefono() {
        return new PERSONAFIS.Telefonos.Telefono();
    }

    /**
     * Create an instance of {@link PROV7 }
     * 
     */
    public PROV7 createPROV7() {
        return new PROV7();
    }

    /**
     * Create an instance of {@link PROV52 }
     * 
     */
    public PROV52 createPROV52() {
        return new PROV52();
    }

    /**
     * Create an instance of {@link PROV17 }
     * 
     */
    public PROV17 createPROV17() {
        return new PROV17();
    }

    /**
     * Create an instance of {@link PROV12 }
     * 
     */
    public PROV12 createPROV12() {
        return new PROV12();
    }

    /**
     * Create an instance of {@link Operacion2325 .Operacion.DiligenciaAduanas }
     * 
     */
    public Operacion2325 .Operacion.DiligenciaAduanas createOperacion2325OperacionDiligenciaAduanas() {
        return new Operacion2325 .Operacion.DiligenciaAduanas();
    }

    /**
     * Create an instance of {@link PERSONAJUR.DocIdentifsPJ }
     * 
     */
    public PERSONAJUR.DocIdentifsPJ createPERSONAJURDocIdentifsPJ() {
        return new PERSONAJUR.DocIdentifsPJ();
    }

    /**
     * Create an instance of {@link PROV9 }
     * 
     */
    public PROV9 createPROV9() {
        return new PROV9();
    }

    /**
     * Create an instance of {@link PROV13 }
     * 
     */
    public PROV13 createPROV13() {
        return new PROV13();
    }

    /**
     * Create an instance of {@link PROV11 }
     * 
     */
    public PROV11 createPROV11() {
        return new PROV11();
    }

    /**
     * Create an instance of {@link PROV23 }
     * 
     */
    public PROV23 createPROV23() {
        return new PROV23();
    }

    /**
     * Create an instance of {@link PROV35 }
     * 
     */
    public PROV35 createPROV35() {
        return new PROV35();
    }

    /**
     * Create an instance of {@link PROV10 }
     * 
     */
    public PROV10 createPROV10() {
        return new PROV10();
    }

    /**
     * Create an instance of {@link PROV14 }
     * 
     */
    public PROV14 createPROV14() {
        return new PROV14();
    }

    /**
     * Create an instance of {@link PROV27 }
     * 
     */
    public PROV27 createPROV27() {
        return new PROV27();
    }

    /**
     * Create an instance of {@link Operacion2325 .Intervinientes.Propietario }
     * 
     */
    public Operacion2325 .Intervinientes.Propietario createOperacion2325IntervinientesPropietario() {
        return new Operacion2325 .Intervinientes.Propietario();
    }

    /**
     * Create an instance of {@link Operacion2325 .Intervinientes.Declarante }
     * 
     */
    public Operacion2325 .Intervinientes.Declarante createOperacion2325IntervinientesDeclarante() {
        return new Operacion2325 .Intervinientes.Declarante();
    }

    /**
     * Create an instance of {@link PROV20 }
     * 
     */
    public PROV20 createPROV20() {
        return new PROV20();
    }

    /**
     * Create an instance of {@link CABECERAOP }
     * 
     */
    public CABECERAOP createCABECERAOP() {
        return new CABECERAOP();
    }

    /**
     * Create an instance of {@link PROV37 }
     * 
     */
    public PROV37 createPROV37() {
        return new PROV37();
    }

    /**
     * Create an instance of {@link DOCIDENTIFPJ }
     * 
     */
    public DOCIDENTIFPJ createDOCIDENTIFPJ() {
        return new DOCIDENTIFPJ();
    }

    /**
     * Create an instance of {@link Operacion2325 .Operacion.MediosPago.MedioPago }
     * 
     */
    public Operacion2325 .Operacion.MediosPago.MedioPago createOperacion2325OperacionMediosPagoMedioPago() {
        return new Operacion2325 .Operacion.MediosPago.MedioPago();
    }

    /**
     * Create an instance of {@link PERSONAFIS.DomiciliosPF }
     * 
     */
    public PERSONAFIS.DomiciliosPF createPERSONAFISDomiciliosPF() {
        return new PERSONAFIS.DomiciliosPF();
    }

    /**
     * Create an instance of {@link PROV38 }
     * 
     */
    public PROV38 createPROV38() {
        return new PROV38();
    }

    /**
     * Create an instance of {@link Operacion2325 .Operacion.OrigenDestinoMediosPago }
     * 
     */
    public Operacion2325 .Operacion.OrigenDestinoMediosPago createOperacion2325OperacionOrigenDestinoMediosPago() {
        return new Operacion2325 .Operacion.OrigenDestinoMediosPago();
    }

    /**
     * Create an instance of {@link PROV8 }
     * 
     */
    public PROV8 createPROV8() {
        return new PROV8();
    }

    /**
     * Create an instance of {@link PROV24 }
     * 
     */
    public PROV24 createPROV24() {
        return new PROV24();
    }

    /**
     * Create an instance of {@link DOMICILIOCP }
     * 
     */
    public DOMICILIOCP createDOMICILIOCP() {
        return new DOMICILIOCP();
    }

    /**
     * Create an instance of {@link PROV43 }
     * 
     */
    public PROV43 createPROV43() {
        return new PROV43();
    }

    /**
     * Create an instance of {@link CABECERAOP.Caracteristicas }
     * 
     */
    public CABECERAOP.Caracteristicas createCABECERAOPCaracteristicas() {
        return new CABECERAOP.Caracteristicas();
    }

    /**
     * Create an instance of {@link PROV32 }
     * 
     */
    public PROV32 createPROV32() {
        return new PROV32();
    }

    /**
     * Create an instance of {@link PROV5 }
     * 
     */
    public PROV5 createPROV5() {
        return new PROV5();
    }

    /**
     * Create an instance of {@link CABECERAOPS1 .Caracteristicas }
     * 
     */
    public CABECERAOPS1 .Caracteristicas createCABECERAOPS1Caracteristicas() {
        return new CABECERAOPS1 .Caracteristicas();
    }

    /**
     * Create an instance of {@link PROV46 }
     * 
     */
    public PROV46 createPROV46() {
        return new PROV46();
    }

    /**
     * Create an instance of {@link PERSONAJUR.DocIdentifsPJ.DocIdentifPJ }
     * 
     */
    public PERSONAJUR.DocIdentifsPJ.DocIdentifPJ createPERSONAJURDocIdentifsPJDocIdentifPJ() {
        return new PERSONAJUR.DocIdentifsPJ.DocIdentifPJ();
    }

    /**
     * Create an instance of {@link DOCIDENTIF }
     * 
     */
    public DOCIDENTIF createDOCIDENTIF() {
        return new DOCIDENTIF();
    }

    /**
     * Create an instance of {@link PROV28 }
     * 
     */
    public PROV28 createPROV28() {
        return new PROV28();
    }

    /**
     * Create an instance of {@link Operacion2325 .Operacion.MovMediosPagos }
     * 
     */
    public Operacion2325 .Operacion.MovMediosPagos createOperacion2325OperacionMovMediosPagos() {
        return new Operacion2325 .Operacion.MovMediosPagos();
    }

    /**
     * Create an instance of {@link PROV15 }
     * 
     */
    public PROV15 createPROV15() {
        return new PROV15();
    }

    /**
     * Create an instance of {@link Operacion2325 .Intervinientes }
     * 
     */
    public Operacion2325 .Intervinientes createOperacion2325Intervinientes() {
        return new Operacion2325 .Intervinientes();
    }

    /**
     * Create an instance of {@link TELEFONO }
     * 
     */
    public TELEFONO createTELEFONO() {
        return new TELEFONO();
    }

    /**
     * Create an instance of {@link PROV3 }
     * 
     */
    public PROV3 createPROV3() {
        return new PROV3();
    }

}
