//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.13 at 01:15:20 PM CET 
//


package com.reportingtool.xml.dmo;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Operacion">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="NumOperacion">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                         &lt;totalDigits value="5"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="TipoOperacion">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                         &lt;totalDigits value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CodigoS1">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="25"/>
 *                         &lt;minLength value="25"/>
 *                         &lt;pattern value="[0][0][0][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z]"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="MovMediosPagos">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="FechaMovimiento" type="{http://www.sepblac.es/DMO}FECHA_GEN"/>
 *                             &lt;element name="TipoMovimiento" type="{http://www.sepblac.es/DMO}TIPMOVMP_ENUM"/>
 *                             &lt;element name="CodAduanaPasoFronterizo" type="{http://www.sepblac.es/DMO}ADU_PF_ENUM"/>
 *                             &lt;element name="AduanaPasoFronterizo" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="80"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="MediosPago">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ImporteTotalCifra">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                   &lt;totalDigits value="16"/>
 *                                   &lt;fractionDigits value="2"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="DiligenciaAduanas" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CodAduanaControl" type="{http://www.sepblac.es/DMO}ADUANACONTROL_ENUM"/>
 *                             &lt;element name="AduanaControl" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="80"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Verificado" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="FechaDiligenciaAduanas" type="{http://www.sepblac.es/DMO}FECHA_GEN"/>
 *                             &lt;element name="HoraDiligenciaAduanas" type="{http://www.sepblac.es/DMO}HORA"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Intervinientes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Declarante" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PersonaFisica">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CDPERSONA">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="10"/>
 *                                             &lt;minLength value="1"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="NombreRazonSocial" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="80"/>
 *                                             &lt;minLength value="1"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="PrimerApellido" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="40"/>
 *                                             &lt;minLength value="1"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="SegundoApellido" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="40"/>
 *                                             &lt;minLength value="1"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="DocIdentificativo" type="{http://www.sepblac.es/DMO}DOCIDENTIF_PF"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Propietario" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence minOccurs="0">
 *                             &lt;element name="PersonaFisica" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CDPERSONA">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="10"/>
 *                                             &lt;minLength value="1"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="NombreRazonSocial" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="80"/>
 *                                             &lt;minLength value="1"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="PrimerApellido" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="40"/>
 *                                             &lt;minLength value="1"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="SegundoApellido" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="40"/>
 *                                             &lt;minLength value="1"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="DocIdentificativo" type="{http://www.sepblac.es/DMO}DOCIDENTIF_PF"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Sociedad" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CDPERSONA">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="10"/>
 *                                             &lt;minLength value="1"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="RazonSocial">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="80"/>
 *                                             &lt;minLength value="1"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="DocIdentificativo" type="{http://www.sepblac.es/DMO}DOCIDENTIF_PJ"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "operacion",
    "intervinientes"
})
@XmlRootElement(name = "Operacion26y27")
public class Operacion26Y27 {

    @XmlElement(name = "Operacion", required = true)
    protected Operacion26Y27 .Operacion operacion;
    @XmlElement(name = "Intervinientes", required = true)
    protected Operacion26Y27 .Intervinientes intervinientes;

    /**
     * Gets the value of the operacion property.
     * 
     * @return
     *     possible object is
     *     {@link Operacion26Y27 .Operacion }
     *     
     */
    public Operacion26Y27 .Operacion getOperacion() {
        return operacion;
    }

    /**
     * Sets the value of the operacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Operacion26Y27 .Operacion }
     *     
     */
    public void setOperacion(Operacion26Y27 .Operacion value) {
        this.operacion = value;
    }

    /**
     * Gets the value of the intervinientes property.
     * 
     * @return
     *     possible object is
     *     {@link Operacion26Y27 .Intervinientes }
     *     
     */
    public Operacion26Y27 .Intervinientes getIntervinientes() {
        return intervinientes;
    }

    /**
     * Sets the value of the intervinientes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Operacion26Y27 .Intervinientes }
     *     
     */
    public void setIntervinientes(Operacion26Y27 .Intervinientes value) {
        this.intervinientes = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Declarante" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="PersonaFisica">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CDPERSONA">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="10"/>
     *                                   &lt;minLength value="1"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="NombreRazonSocial" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="80"/>
     *                                   &lt;minLength value="1"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="PrimerApellido" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="40"/>
     *                                   &lt;minLength value="1"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="SegundoApellido" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="40"/>
     *                                   &lt;minLength value="1"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="DocIdentificativo" type="{http://www.sepblac.es/DMO}DOCIDENTIF_PF"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Propietario" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence minOccurs="0">
     *                   &lt;element name="PersonaFisica" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CDPERSONA">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="10"/>
     *                                   &lt;minLength value="1"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="NombreRazonSocial" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="80"/>
     *                                   &lt;minLength value="1"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="PrimerApellido" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="40"/>
     *                                   &lt;minLength value="1"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="SegundoApellido" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="40"/>
     *                                   &lt;minLength value="1"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="DocIdentificativo" type="{http://www.sepblac.es/DMO}DOCIDENTIF_PF"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Sociedad" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CDPERSONA">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="10"/>
     *                                   &lt;minLength value="1"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="RazonSocial">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="80"/>
     *                                   &lt;minLength value="1"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="DocIdentificativo" type="{http://www.sepblac.es/DMO}DOCIDENTIF_PJ"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "declarante",
        "propietario"
    })
    public static class Intervinientes {

        @XmlElement(name = "Declarante")
        protected Operacion26Y27 .Intervinientes.Declarante declarante;
        @XmlElement(name = "Propietario")
        protected Operacion26Y27 .Intervinientes.Propietario propietario;

        /**
         * Gets the value of the declarante property.
         * 
         * @return
         *     possible object is
         *     {@link Operacion26Y27 .Intervinientes.Declarante }
         *     
         */
        public Operacion26Y27 .Intervinientes.Declarante getDeclarante() {
            return declarante;
        }

        /**
         * Sets the value of the declarante property.
         * 
         * @param value
         *     allowed object is
         *     {@link Operacion26Y27 .Intervinientes.Declarante }
         *     
         */
        public void setDeclarante(Operacion26Y27 .Intervinientes.Declarante value) {
            this.declarante = value;
        }

        /**
         * Gets the value of the propietario property.
         * 
         * @return
         *     possible object is
         *     {@link Operacion26Y27 .Intervinientes.Propietario }
         *     
         */
        public Operacion26Y27 .Intervinientes.Propietario getPropietario() {
            return propietario;
        }

        /**
         * Sets the value of the propietario property.
         * 
         * @param value
         *     allowed object is
         *     {@link Operacion26Y27 .Intervinientes.Propietario }
         *     
         */
        public void setPropietario(Operacion26Y27 .Intervinientes.Propietario value) {
            this.propietario = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="PersonaFisica">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CDPERSONA">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="10"/>
         *                         &lt;minLength value="1"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="NombreRazonSocial" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="80"/>
         *                         &lt;minLength value="1"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="PrimerApellido" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="40"/>
         *                         &lt;minLength value="1"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="SegundoApellido" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="40"/>
         *                         &lt;minLength value="1"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="DocIdentificativo" type="{http://www.sepblac.es/DMO}DOCIDENTIF_PF"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "personaFisica"
        })
        public static class Declarante {

            @XmlElement(name = "PersonaFisica", required = true)
            protected Operacion26Y27 .Intervinientes.Declarante.PersonaFisica personaFisica;

            /**
             * Gets the value of the personaFisica property.
             * 
             * @return
             *     possible object is
             *     {@link Operacion26Y27 .Intervinientes.Declarante.PersonaFisica }
             *     
             */
            public Operacion26Y27 .Intervinientes.Declarante.PersonaFisica getPersonaFisica() {
                return personaFisica;
            }

            /**
             * Sets the value of the personaFisica property.
             * 
             * @param value
             *     allowed object is
             *     {@link Operacion26Y27 .Intervinientes.Declarante.PersonaFisica }
             *     
             */
            public void setPersonaFisica(Operacion26Y27 .Intervinientes.Declarante.PersonaFisica value) {
                this.personaFisica = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CDPERSONA">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="10"/>
             *               &lt;minLength value="1"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="NombreRazonSocial" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="80"/>
             *               &lt;minLength value="1"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="PrimerApellido" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="40"/>
             *               &lt;minLength value="1"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="SegundoApellido" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="40"/>
             *               &lt;minLength value="1"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="DocIdentificativo" type="{http://www.sepblac.es/DMO}DOCIDENTIF_PF"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "cdpersona",
                "nombreRazonSocial",
                "primerApellido",
                "segundoApellido",
                "docIdentificativo"
            })
            public static class PersonaFisica {

                @XmlElement(name = "CDPERSONA", required = true)
                protected String cdpersona;
                @XmlElement(name = "NombreRazonSocial")
                protected String nombreRazonSocial;
                @XmlElement(name = "PrimerApellido")
                protected String primerApellido;
                @XmlElement(name = "SegundoApellido")
                protected String segundoApellido;
                @XmlElement(name = "DocIdentificativo", required = true)
                protected DOCIDENTIFPF docIdentificativo;

                /**
                 * Gets the value of the cdpersona property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCDPERSONA() {
                    return cdpersona;
                }

                /**
                 * Sets the value of the cdpersona property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCDPERSONA(String value) {
                    this.cdpersona = value;
                }

                /**
                 * Gets the value of the nombreRazonSocial property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNombreRazonSocial() {
                    return nombreRazonSocial;
                }

                /**
                 * Sets the value of the nombreRazonSocial property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNombreRazonSocial(String value) {
                    this.nombreRazonSocial = value;
                }

                /**
                 * Gets the value of the primerApellido property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPrimerApellido() {
                    return primerApellido;
                }

                /**
                 * Sets the value of the primerApellido property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPrimerApellido(String value) {
                    this.primerApellido = value;
                }

                /**
                 * Gets the value of the segundoApellido property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSegundoApellido() {
                    return segundoApellido;
                }

                /**
                 * Sets the value of the segundoApellido property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSegundoApellido(String value) {
                    this.segundoApellido = value;
                }

                /**
                 * Gets the value of the docIdentificativo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link DOCIDENTIFPF }
                 *     
                 */
                public DOCIDENTIFPF getDocIdentificativo() {
                    return docIdentificativo;
                }

                /**
                 * Sets the value of the docIdentificativo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link DOCIDENTIFPF }
                 *     
                 */
                public void setDocIdentificativo(DOCIDENTIFPF value) {
                    this.docIdentificativo = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence minOccurs="0">
         *         &lt;element name="PersonaFisica" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CDPERSONA">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="10"/>
         *                         &lt;minLength value="1"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="NombreRazonSocial" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="80"/>
         *                         &lt;minLength value="1"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="PrimerApellido" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="40"/>
         *                         &lt;minLength value="1"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="SegundoApellido" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="40"/>
         *                         &lt;minLength value="1"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="DocIdentificativo" type="{http://www.sepblac.es/DMO}DOCIDENTIF_PF"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Sociedad" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CDPERSONA">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="10"/>
         *                         &lt;minLength value="1"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="RazonSocial">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="80"/>
         *                         &lt;minLength value="1"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="DocIdentificativo" type="{http://www.sepblac.es/DMO}DOCIDENTIF_PJ"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "personaFisica",
            "sociedad"
        })
        public static class Propietario {

            @XmlElement(name = "PersonaFisica")
            protected Operacion26Y27 .Intervinientes.Propietario.PersonaFisica personaFisica;
            @XmlElement(name = "Sociedad")
            protected Operacion26Y27 .Intervinientes.Propietario.Sociedad sociedad;

            /**
             * Gets the value of the personaFisica property.
             * 
             * @return
             *     possible object is
             *     {@link Operacion26Y27 .Intervinientes.Propietario.PersonaFisica }
             *     
             */
            public Operacion26Y27 .Intervinientes.Propietario.PersonaFisica getPersonaFisica() {
                return personaFisica;
            }

            /**
             * Sets the value of the personaFisica property.
             * 
             * @param value
             *     allowed object is
             *     {@link Operacion26Y27 .Intervinientes.Propietario.PersonaFisica }
             *     
             */
            public void setPersonaFisica(Operacion26Y27 .Intervinientes.Propietario.PersonaFisica value) {
                this.personaFisica = value;
            }

            /**
             * Gets the value of the sociedad property.
             * 
             * @return
             *     possible object is
             *     {@link Operacion26Y27 .Intervinientes.Propietario.Sociedad }
             *     
             */
            public Operacion26Y27 .Intervinientes.Propietario.Sociedad getSociedad() {
                return sociedad;
            }

            /**
             * Sets the value of the sociedad property.
             * 
             * @param value
             *     allowed object is
             *     {@link Operacion26Y27 .Intervinientes.Propietario.Sociedad }
             *     
             */
            public void setSociedad(Operacion26Y27 .Intervinientes.Propietario.Sociedad value) {
                this.sociedad = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CDPERSONA">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="10"/>
             *               &lt;minLength value="1"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="NombreRazonSocial" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="80"/>
             *               &lt;minLength value="1"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="PrimerApellido" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="40"/>
             *               &lt;minLength value="1"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="SegundoApellido" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="40"/>
             *               &lt;minLength value="1"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="DocIdentificativo" type="{http://www.sepblac.es/DMO}DOCIDENTIF_PF"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "cdpersona",
                "nombreRazonSocial",
                "primerApellido",
                "segundoApellido",
                "docIdentificativo"
            })
            public static class PersonaFisica {

                @XmlElement(name = "CDPERSONA", required = true)
                protected String cdpersona;
                @XmlElement(name = "NombreRazonSocial")
                protected String nombreRazonSocial;
                @XmlElement(name = "PrimerApellido")
                protected String primerApellido;
                @XmlElement(name = "SegundoApellido")
                protected String segundoApellido;
                @XmlElement(name = "DocIdentificativo", required = true)
                protected DOCIDENTIFPF docIdentificativo;

                /**
                 * Gets the value of the cdpersona property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCDPERSONA() {
                    return cdpersona;
                }

                /**
                 * Sets the value of the cdpersona property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCDPERSONA(String value) {
                    this.cdpersona = value;
                }

                /**
                 * Gets the value of the nombreRazonSocial property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNombreRazonSocial() {
                    return nombreRazonSocial;
                }

                /**
                 * Sets the value of the nombreRazonSocial property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNombreRazonSocial(String value) {
                    this.nombreRazonSocial = value;
                }

                /**
                 * Gets the value of the primerApellido property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPrimerApellido() {
                    return primerApellido;
                }

                /**
                 * Sets the value of the primerApellido property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPrimerApellido(String value) {
                    this.primerApellido = value;
                }

                /**
                 * Gets the value of the segundoApellido property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSegundoApellido() {
                    return segundoApellido;
                }

                /**
                 * Sets the value of the segundoApellido property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSegundoApellido(String value) {
                    this.segundoApellido = value;
                }

                /**
                 * Gets the value of the docIdentificativo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link DOCIDENTIFPF }
                 *     
                 */
                public DOCIDENTIFPF getDocIdentificativo() {
                    return docIdentificativo;
                }

                /**
                 * Sets the value of the docIdentificativo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link DOCIDENTIFPF }
                 *     
                 */
                public void setDocIdentificativo(DOCIDENTIFPF value) {
                    this.docIdentificativo = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CDPERSONA">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="10"/>
             *               &lt;minLength value="1"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="RazonSocial">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="80"/>
             *               &lt;minLength value="1"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="DocIdentificativo" type="{http://www.sepblac.es/DMO}DOCIDENTIF_PJ"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "cdpersona",
                "razonSocial",
                "docIdentificativo"
            })
            public static class Sociedad {

                @XmlElement(name = "CDPERSONA", required = true)
                protected String cdpersona;
                @XmlElement(name = "RazonSocial", required = true)
                protected String razonSocial;
                @XmlElement(name = "DocIdentificativo", required = true)
                protected DOCIDENTIFPJ docIdentificativo;

                /**
                 * Gets the value of the cdpersona property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCDPERSONA() {
                    return cdpersona;
                }

                /**
                 * Sets the value of the cdpersona property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCDPERSONA(String value) {
                    this.cdpersona = value;
                }

                /**
                 * Gets the value of the razonSocial property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRazonSocial() {
                    return razonSocial;
                }

                /**
                 * Sets the value of the razonSocial property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRazonSocial(String value) {
                    this.razonSocial = value;
                }

                /**
                 * Gets the value of the docIdentificativo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link DOCIDENTIFPJ }
                 *     
                 */
                public DOCIDENTIFPJ getDocIdentificativo() {
                    return docIdentificativo;
                }

                /**
                 * Sets the value of the docIdentificativo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link DOCIDENTIFPJ }
                 *     
                 */
                public void setDocIdentificativo(DOCIDENTIFPJ value) {
                    this.docIdentificativo = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="NumOperacion">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *               &lt;totalDigits value="5"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="TipoOperacion">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *               &lt;totalDigits value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CodigoS1">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="25"/>
     *               &lt;minLength value="25"/>
     *               &lt;pattern value="[0][0][0][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z][0-9|a-z|A-Z]"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="MovMediosPagos">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="FechaMovimiento" type="{http://www.sepblac.es/DMO}FECHA_GEN"/>
     *                   &lt;element name="TipoMovimiento" type="{http://www.sepblac.es/DMO}TIPMOVMP_ENUM"/>
     *                   &lt;element name="CodAduanaPasoFronterizo" type="{http://www.sepblac.es/DMO}ADU_PF_ENUM"/>
     *                   &lt;element name="AduanaPasoFronterizo" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="80"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="MediosPago">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ImporteTotalCifra">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                         &lt;totalDigits value="16"/>
     *                         &lt;fractionDigits value="2"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="DiligenciaAduanas" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CodAduanaControl" type="{http://www.sepblac.es/DMO}ADUANACONTROL_ENUM"/>
     *                   &lt;element name="AduanaControl" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="80"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Verificado" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="FechaDiligenciaAduanas" type="{http://www.sepblac.es/DMO}FECHA_GEN"/>
     *                   &lt;element name="HoraDiligenciaAduanas" type="{http://www.sepblac.es/DMO}HORA"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "numOperacion",
        "tipoOperacion",
        "codigoS1",
        "movMediosPagos",
        "mediosPago",
        "diligenciaAduanas"
    })
    public static class Operacion {

        @XmlElement(name = "NumOperacion")
        protected int numOperacion;
        @XmlElement(name = "TipoOperacion")
        protected int tipoOperacion;
        @XmlElement(name = "CodigoS1", required = true)
        protected String codigoS1;
        @XmlElement(name = "MovMediosPagos", required = true)
        protected Operacion26Y27 .Operacion.MovMediosPagos movMediosPagos;
        @XmlElement(name = "MediosPago", required = true)
        protected Operacion26Y27 .Operacion.MediosPago mediosPago;
        @XmlElement(name = "DiligenciaAduanas")
        protected Operacion26Y27 .Operacion.DiligenciaAduanas diligenciaAduanas;

        /**
         * Gets the value of the numOperacion property.
         * 
         */
        public int getNumOperacion() {
            return numOperacion;
        }

        /**
         * Sets the value of the numOperacion property.
         * 
         */
        public void setNumOperacion(int value) {
            this.numOperacion = value;
        }

        /**
         * Gets the value of the tipoOperacion property.
         * 
         */
        public int getTipoOperacion() {
            return tipoOperacion;
        }

        /**
         * Sets the value of the tipoOperacion property.
         * 
         */
        public void setTipoOperacion(int value) {
            this.tipoOperacion = value;
        }

        /**
         * Gets the value of the codigoS1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodigoS1() {
            return codigoS1;
        }

        /**
         * Sets the value of the codigoS1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodigoS1(String value) {
            this.codigoS1 = value;
        }

        /**
         * Gets the value of the movMediosPagos property.
         * 
         * @return
         *     possible object is
         *     {@link Operacion26Y27 .Operacion.MovMediosPagos }
         *     
         */
        public Operacion26Y27 .Operacion.MovMediosPagos getMovMediosPagos() {
            return movMediosPagos;
        }

        /**
         * Sets the value of the movMediosPagos property.
         * 
         * @param value
         *     allowed object is
         *     {@link Operacion26Y27 .Operacion.MovMediosPagos }
         *     
         */
        public void setMovMediosPagos(Operacion26Y27 .Operacion.MovMediosPagos value) {
            this.movMediosPagos = value;
        }

        /**
         * Gets the value of the mediosPago property.
         * 
         * @return
         *     possible object is
         *     {@link Operacion26Y27 .Operacion.MediosPago }
         *     
         */
        public Operacion26Y27 .Operacion.MediosPago getMediosPago() {
            return mediosPago;
        }

        /**
         * Sets the value of the mediosPago property.
         * 
         * @param value
         *     allowed object is
         *     {@link Operacion26Y27 .Operacion.MediosPago }
         *     
         */
        public void setMediosPago(Operacion26Y27 .Operacion.MediosPago value) {
            this.mediosPago = value;
        }

        /**
         * Gets the value of the diligenciaAduanas property.
         * 
         * @return
         *     possible object is
         *     {@link Operacion26Y27 .Operacion.DiligenciaAduanas }
         *     
         */
        public Operacion26Y27 .Operacion.DiligenciaAduanas getDiligenciaAduanas() {
            return diligenciaAduanas;
        }

        /**
         * Sets the value of the diligenciaAduanas property.
         * 
         * @param value
         *     allowed object is
         *     {@link Operacion26Y27 .Operacion.DiligenciaAduanas }
         *     
         */
        public void setDiligenciaAduanas(Operacion26Y27 .Operacion.DiligenciaAduanas value) {
            this.diligenciaAduanas = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CodAduanaControl" type="{http://www.sepblac.es/DMO}ADUANACONTROL_ENUM"/>
         *         &lt;element name="AduanaControl" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="80"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Verificado" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="FechaDiligenciaAduanas" type="{http://www.sepblac.es/DMO}FECHA_GEN"/>
         *         &lt;element name="HoraDiligenciaAduanas" type="{http://www.sepblac.es/DMO}HORA"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "codAduanaControl",
            "aduanaControl",
            "verificado",
            "fechaDiligenciaAduanas",
            "horaDiligenciaAduanas"
        })
        public static class DiligenciaAduanas {

            @XmlElement(name = "CodAduanaControl")
            protected int codAduanaControl;
            @XmlElement(name = "AduanaControl")
            protected String aduanaControl;
            @XmlElement(name = "Verificado")
            protected boolean verificado;
            @XmlElement(name = "FechaDiligenciaAduanas", required = true)
            protected String fechaDiligenciaAduanas;
            @XmlElement(name = "HoraDiligenciaAduanas", required = true)
            protected String horaDiligenciaAduanas;

            /**
             * Gets the value of the codAduanaControl property.
             * 
             */
            public int getCodAduanaControl() {
                return codAduanaControl;
            }

            /**
             * Sets the value of the codAduanaControl property.
             * 
             */
            public void setCodAduanaControl(int value) {
                this.codAduanaControl = value;
            }

            /**
             * Gets the value of the aduanaControl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAduanaControl() {
                return aduanaControl;
            }

            /**
             * Sets the value of the aduanaControl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAduanaControl(String value) {
                this.aduanaControl = value;
            }

            /**
             * Gets the value of the verificado property.
             * 
             */
            public boolean isVerificado() {
                return verificado;
            }

            /**
             * Sets the value of the verificado property.
             * 
             */
            public void setVerificado(boolean value) {
                this.verificado = value;
            }

            /**
             * Gets the value of the fechaDiligenciaAduanas property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFechaDiligenciaAduanas() {
                return fechaDiligenciaAduanas;
            }

            /**
             * Sets the value of the fechaDiligenciaAduanas property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFechaDiligenciaAduanas(String value) {
                this.fechaDiligenciaAduanas = value;
            }

            /**
             * Gets the value of the horaDiligenciaAduanas property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHoraDiligenciaAduanas() {
                return horaDiligenciaAduanas;
            }

            /**
             * Sets the value of the horaDiligenciaAduanas property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHoraDiligenciaAduanas(String value) {
                this.horaDiligenciaAduanas = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ImporteTotalCifra">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *               &lt;totalDigits value="16"/>
         *               &lt;fractionDigits value="2"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "importeTotalCifra"
        })
        public static class MediosPago {

            @XmlElement(name = "ImporteTotalCifra", required = true)
            protected BigDecimal importeTotalCifra;

            /**
             * Gets the value of the importeTotalCifra property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getImporteTotalCifra() {
                return importeTotalCifra;
            }

            /**
             * Sets the value of the importeTotalCifra property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setImporteTotalCifra(BigDecimal value) {
                this.importeTotalCifra = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="FechaMovimiento" type="{http://www.sepblac.es/DMO}FECHA_GEN"/>
         *         &lt;element name="TipoMovimiento" type="{http://www.sepblac.es/DMO}TIPMOVMP_ENUM"/>
         *         &lt;element name="CodAduanaPasoFronterizo" type="{http://www.sepblac.es/DMO}ADU_PF_ENUM"/>
         *         &lt;element name="AduanaPasoFronterizo" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="80"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fechaMovimiento",
            "tipoMovimiento",
            "codAduanaPasoFronterizo",
            "aduanaPasoFronterizo"
        })
        public static class MovMediosPagos {

            @XmlElement(name = "FechaMovimiento", required = true)
            protected String fechaMovimiento;
            @XmlElement(name = "TipoMovimiento")
            protected int tipoMovimiento;
            @XmlElement(name = "CodAduanaPasoFronterizo")
            protected int codAduanaPasoFronterizo;
            @XmlElement(name = "AduanaPasoFronterizo")
            protected String aduanaPasoFronterizo;

            /**
             * Gets the value of the fechaMovimiento property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFechaMovimiento() {
                return fechaMovimiento;
            }

            /**
             * Sets the value of the fechaMovimiento property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFechaMovimiento(String value) {
                this.fechaMovimiento = value;
            }

            /**
             * Gets the value of the tipoMovimiento property.
             * 
             */
            public int getTipoMovimiento() {
                return tipoMovimiento;
            }

            /**
             * Sets the value of the tipoMovimiento property.
             * 
             */
            public void setTipoMovimiento(int value) {
                this.tipoMovimiento = value;
            }

            /**
             * Gets the value of the codAduanaPasoFronterizo property.
             * 
             */
            public int getCodAduanaPasoFronterizo() {
                return codAduanaPasoFronterizo;
            }

            /**
             * Sets the value of the codAduanaPasoFronterizo property.
             * 
             */
            public void setCodAduanaPasoFronterizo(int value) {
                this.codAduanaPasoFronterizo = value;
            }

            /**
             * Gets the value of the aduanaPasoFronterizo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAduanaPasoFronterizo() {
                return aduanaPasoFronterizo;
            }

            /**
             * Sets the value of the aduanaPasoFronterizo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAduanaPasoFronterizo(String value) {
                this.aduanaPasoFronterizo = value;
            }

        }

    }

}
