//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.13 at 01:15:20 PM CET 
//


package com.reportingtool.xml.dmo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Operacion" type="{http://www.sepblac.es/DMO}CABECERAOP_S1"/>
 *         &lt;element name="Intervinientes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PersonaFisica" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CDPERSONA">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="10"/>
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Nombre" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="80"/>
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="PrimerApellido" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="40"/>
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="SegundoApellido" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="40"/>
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Pais" type="{http://www.sepblac.es/DMO}PAIS_ENUM" minOccurs="0"/>
 *                             &lt;element name="DocIdentifsPF">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="DocIdentifPF" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;extension base="{http://www.sepblac.es/DMO}DOCIDENTIF_PF">
 *                                             &lt;/extension>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="DomiciliosPF">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="DomicilioPF" type="{http://www.sepblac.es/DMO}DOMICILIO" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Telefonos">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Telefono" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;extension base="{http://www.sepblac.es/DMO}TELEFONO">
 *                                             &lt;/extension>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Relacion" type="{http://www.sepblac.es/DMO}REL_PER_CUENTA_ENUM" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Sociedad" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CDPERSONA">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="10"/>
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="RazonSocial">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="80"/>
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="PaisNacionalidad" type="{http://www.sepblac.es/DMO}PAIS_ENUM" minOccurs="0"/>
 *                             &lt;element name="DocIdentifsPJ">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="DocIdentifPJ" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;extension base="{http://www.sepblac.es/DMO}DOCIDENTIF_PJ">
 *                                             &lt;/extension>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="DomiciliosPJ">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="DomicilioPJ" type="{http://www.sepblac.es/DMO}DOMICILIO" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Telefonos">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Telefono" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;extension base="{http://www.sepblac.es/DMO}TELEFONO">
 *                                             &lt;/extension>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Relacion" type="{http://www.sepblac.es/DMO}REL_PER_CUENTA_ENUM" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "operacion",
    "intervinientes"
})
@XmlRootElement(name = "Operacion28y29")
public class Operacion28Y29 {

    @XmlElement(name = "Operacion", required = true)
    protected CABECERAOPS1 operacion;
    @XmlElement(name = "Intervinientes", required = true)
    protected Operacion28Y29 .Intervinientes intervinientes;

    /**
     * Gets the value of the operacion property.
     * 
     * @return
     *     possible object is
     *     {@link CABECERAOPS1 }
     *     
     */
    public CABECERAOPS1 getOperacion() {
        return operacion;
    }

    /**
     * Sets the value of the operacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link CABECERAOPS1 }
     *     
     */
    public void setOperacion(CABECERAOPS1 value) {
        this.operacion = value;
    }

    /**
     * Gets the value of the intervinientes property.
     * 
     * @return
     *     possible object is
     *     {@link Operacion28Y29 .Intervinientes }
     *     
     */
    public Operacion28Y29 .Intervinientes getIntervinientes() {
        return intervinientes;
    }

    /**
     * Sets the value of the intervinientes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Operacion28Y29 .Intervinientes }
     *     
     */
    public void setIntervinientes(Operacion28Y29 .Intervinientes value) {
        this.intervinientes = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PersonaFisica" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CDPERSONA">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="10"/>
     *                         &lt;minLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Nombre" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="80"/>
     *                         &lt;minLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="PrimerApellido" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="40"/>
     *                         &lt;minLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="SegundoApellido" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="40"/>
     *                         &lt;minLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Pais" type="{http://www.sepblac.es/DMO}PAIS_ENUM" minOccurs="0"/>
     *                   &lt;element name="DocIdentifsPF">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="DocIdentifPF" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;extension base="{http://www.sepblac.es/DMO}DOCIDENTIF_PF">
     *                                   &lt;/extension>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="DomiciliosPF">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="DomicilioPF" type="{http://www.sepblac.es/DMO}DOMICILIO" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Telefonos">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Telefono" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;extension base="{http://www.sepblac.es/DMO}TELEFONO">
     *                                   &lt;/extension>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Relacion" type="{http://www.sepblac.es/DMO}REL_PER_CUENTA_ENUM" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Sociedad" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CDPERSONA">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="10"/>
     *                         &lt;minLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="RazonSocial">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="80"/>
     *                         &lt;minLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="PaisNacionalidad" type="{http://www.sepblac.es/DMO}PAIS_ENUM" minOccurs="0"/>
     *                   &lt;element name="DocIdentifsPJ">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="DocIdentifPJ" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;extension base="{http://www.sepblac.es/DMO}DOCIDENTIF_PJ">
     *                                   &lt;/extension>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="DomiciliosPJ">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="DomicilioPJ" type="{http://www.sepblac.es/DMO}DOMICILIO" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Telefonos">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Telefono" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;extension base="{http://www.sepblac.es/DMO}TELEFONO">
     *                                   &lt;/extension>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Relacion" type="{http://www.sepblac.es/DMO}REL_PER_CUENTA_ENUM" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "personaFisica",
        "sociedad"
    })
    public static class Intervinientes {

        @XmlElement(name = "PersonaFisica")
        protected List<Operacion28Y29 .Intervinientes.PersonaFisica> personaFisica;
        @XmlElement(name = "Sociedad")
        protected List<Operacion28Y29 .Intervinientes.Sociedad> sociedad;

        /**
         * Gets the value of the personaFisica property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the personaFisica property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPersonaFisica().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Operacion28Y29 .Intervinientes.PersonaFisica }
         * 
         * 
         */
        public List<Operacion28Y29 .Intervinientes.PersonaFisica> getPersonaFisica() {
            if (personaFisica == null) {
                personaFisica = new ArrayList<Operacion28Y29 .Intervinientes.PersonaFisica>();
            }
            return this.personaFisica;
        }

        /**
         * Gets the value of the sociedad property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sociedad property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSociedad().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Operacion28Y29 .Intervinientes.Sociedad }
         * 
         * 
         */
        public List<Operacion28Y29 .Intervinientes.Sociedad> getSociedad() {
            if (sociedad == null) {
                sociedad = new ArrayList<Operacion28Y29 .Intervinientes.Sociedad>();
            }
            return this.sociedad;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CDPERSONA">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="10"/>
         *               &lt;minLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Nombre" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="80"/>
         *               &lt;minLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="PrimerApellido" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="40"/>
         *               &lt;minLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="SegundoApellido" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="40"/>
         *               &lt;minLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Pais" type="{http://www.sepblac.es/DMO}PAIS_ENUM" minOccurs="0"/>
         *         &lt;element name="DocIdentifsPF">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="DocIdentifPF" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;extension base="{http://www.sepblac.es/DMO}DOCIDENTIF_PF">
         *                         &lt;/extension>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="DomiciliosPF">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="DomicilioPF" type="{http://www.sepblac.es/DMO}DOMICILIO" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Telefonos">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Telefono" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;extension base="{http://www.sepblac.es/DMO}TELEFONO">
         *                         &lt;/extension>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Relacion" type="{http://www.sepblac.es/DMO}REL_PER_CUENTA_ENUM" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cdpersona",
            "nombre",
            "primerApellido",
            "segundoApellido",
            "pais",
            "docIdentifsPF",
            "domiciliosPF",
            "telefonos",
            "relacion"
        })
        public static class PersonaFisica {

            @XmlElement(name = "CDPERSONA", required = true)
            protected String cdpersona;
            @XmlElement(name = "Nombre")
            protected String nombre;
            @XmlElement(name = "PrimerApellido")
            protected String primerApellido;
            @XmlElement(name = "SegundoApellido")
            protected String segundoApellido;
            @XmlElement(name = "Pais")
            protected String pais;
            @XmlElement(name = "DocIdentifsPF", required = true)
            protected Operacion28Y29 .Intervinientes.PersonaFisica.DocIdentifsPF docIdentifsPF;
            @XmlElement(name = "DomiciliosPF", required = true)
            protected Operacion28Y29 .Intervinientes.PersonaFisica.DomiciliosPF domiciliosPF;
            @XmlElement(name = "Telefonos", required = true)
            protected Operacion28Y29 .Intervinientes.PersonaFisica.Telefonos telefonos;
            @XmlElement(name = "Relacion")
            protected Integer relacion;

            /**
             * Gets the value of the cdpersona property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCDPERSONA() {
                return cdpersona;
            }

            /**
             * Sets the value of the cdpersona property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCDPERSONA(String value) {
                this.cdpersona = value;
            }

            /**
             * Gets the value of the nombre property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNombre() {
                return nombre;
            }

            /**
             * Sets the value of the nombre property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNombre(String value) {
                this.nombre = value;
            }

            /**
             * Gets the value of the primerApellido property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrimerApellido() {
                return primerApellido;
            }

            /**
             * Sets the value of the primerApellido property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrimerApellido(String value) {
                this.primerApellido = value;
            }

            /**
             * Gets the value of the segundoApellido property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSegundoApellido() {
                return segundoApellido;
            }

            /**
             * Sets the value of the segundoApellido property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSegundoApellido(String value) {
                this.segundoApellido = value;
            }

            /**
             * Gets the value of the pais property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPais() {
                return pais;
            }

            /**
             * Sets the value of the pais property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPais(String value) {
                this.pais = value;
            }

            /**
             * Gets the value of the docIdentifsPF property.
             * 
             * @return
             *     possible object is
             *     {@link Operacion28Y29 .Intervinientes.PersonaFisica.DocIdentifsPF }
             *     
             */
            public Operacion28Y29 .Intervinientes.PersonaFisica.DocIdentifsPF getDocIdentifsPF() {
                return docIdentifsPF;
            }

            /**
             * Sets the value of the docIdentifsPF property.
             * 
             * @param value
             *     allowed object is
             *     {@link Operacion28Y29 .Intervinientes.PersonaFisica.DocIdentifsPF }
             *     
             */
            public void setDocIdentifsPF(Operacion28Y29 .Intervinientes.PersonaFisica.DocIdentifsPF value) {
                this.docIdentifsPF = value;
            }

            /**
             * Gets the value of the domiciliosPF property.
             * 
             * @return
             *     possible object is
             *     {@link Operacion28Y29 .Intervinientes.PersonaFisica.DomiciliosPF }
             *     
             */
            public Operacion28Y29 .Intervinientes.PersonaFisica.DomiciliosPF getDomiciliosPF() {
                return domiciliosPF;
            }

            /**
             * Sets the value of the domiciliosPF property.
             * 
             * @param value
             *     allowed object is
             *     {@link Operacion28Y29 .Intervinientes.PersonaFisica.DomiciliosPF }
             *     
             */
            public void setDomiciliosPF(Operacion28Y29 .Intervinientes.PersonaFisica.DomiciliosPF value) {
                this.domiciliosPF = value;
            }

            /**
             * Gets the value of the telefonos property.
             * 
             * @return
             *     possible object is
             *     {@link Operacion28Y29 .Intervinientes.PersonaFisica.Telefonos }
             *     
             */
            public Operacion28Y29 .Intervinientes.PersonaFisica.Telefonos getTelefonos() {
                return telefonos;
            }

            /**
             * Sets the value of the telefonos property.
             * 
             * @param value
             *     allowed object is
             *     {@link Operacion28Y29 .Intervinientes.PersonaFisica.Telefonos }
             *     
             */
            public void setTelefonos(Operacion28Y29 .Intervinientes.PersonaFisica.Telefonos value) {
                this.telefonos = value;
            }

            /**
             * Gets the value of the relacion property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRelacion() {
                return relacion;
            }

            /**
             * Sets the value of the relacion property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRelacion(Integer value) {
                this.relacion = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="DocIdentifPF" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;extension base="{http://www.sepblac.es/DMO}DOCIDENTIF_PF">
             *               &lt;/extension>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "docIdentifPF"
            })
            public static class DocIdentifsPF {

                @XmlElement(name = "DocIdentifPF")
                protected List<Operacion28Y29 .Intervinientes.PersonaFisica.DocIdentifsPF.DocIdentifPF> docIdentifPF;

                /**
                 * Gets the value of the docIdentifPF property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the docIdentifPF property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getDocIdentifPF().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Operacion28Y29 .Intervinientes.PersonaFisica.DocIdentifsPF.DocIdentifPF }
                 * 
                 * 
                 */
                public List<Operacion28Y29 .Intervinientes.PersonaFisica.DocIdentifsPF.DocIdentifPF> getDocIdentifPF() {
                    if (docIdentifPF == null) {
                        docIdentifPF = new ArrayList<Operacion28Y29 .Intervinientes.PersonaFisica.DocIdentifsPF.DocIdentifPF>();
                    }
                    return this.docIdentifPF;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;extension base="{http://www.sepblac.es/DMO}DOCIDENTIF_PF">
                 *     &lt;/extension>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class DocIdentifPF
                    extends DOCIDENTIFPF
                {


                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="DomicilioPF" type="{http://www.sepblac.es/DMO}DOMICILIO" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "domicilioPF"
            })
            public static class DomiciliosPF {

                @XmlElement(name = "DomicilioPF")
                protected List<DOMICILIO> domicilioPF;

                /**
                 * Gets the value of the domicilioPF property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the domicilioPF property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getDomicilioPF().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link DOMICILIO }
                 * 
                 * 
                 */
                public List<DOMICILIO> getDomicilioPF() {
                    if (domicilioPF == null) {
                        domicilioPF = new ArrayList<DOMICILIO>();
                    }
                    return this.domicilioPF;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Telefono" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;extension base="{http://www.sepblac.es/DMO}TELEFONO">
             *               &lt;/extension>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "telefono"
            })
            public static class Telefonos {

                @XmlElement(name = "Telefono")
                protected List<Operacion28Y29 .Intervinientes.PersonaFisica.Telefonos.Telefono> telefono;

                /**
                 * Gets the value of the telefono property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the telefono property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getTelefono().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Operacion28Y29 .Intervinientes.PersonaFisica.Telefonos.Telefono }
                 * 
                 * 
                 */
                public List<Operacion28Y29 .Intervinientes.PersonaFisica.Telefonos.Telefono> getTelefono() {
                    if (telefono == null) {
                        telefono = new ArrayList<Operacion28Y29 .Intervinientes.PersonaFisica.Telefonos.Telefono>();
                    }
                    return this.telefono;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;extension base="{http://www.sepblac.es/DMO}TELEFONO">
                 *     &lt;/extension>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class Telefono
                    extends TELEFONO
                {


                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CDPERSONA">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="10"/>
         *               &lt;minLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="RazonSocial">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="80"/>
         *               &lt;minLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="PaisNacionalidad" type="{http://www.sepblac.es/DMO}PAIS_ENUM" minOccurs="0"/>
         *         &lt;element name="DocIdentifsPJ">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="DocIdentifPJ" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;extension base="{http://www.sepblac.es/DMO}DOCIDENTIF_PJ">
         *                         &lt;/extension>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="DomiciliosPJ">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="DomicilioPJ" type="{http://www.sepblac.es/DMO}DOMICILIO" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Telefonos">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Telefono" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;extension base="{http://www.sepblac.es/DMO}TELEFONO">
         *                         &lt;/extension>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Relacion" type="{http://www.sepblac.es/DMO}REL_PER_CUENTA_ENUM" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cdpersona",
            "razonSocial",
            "paisNacionalidad",
            "docIdentifsPJ",
            "domiciliosPJ",
            "telefonos",
            "relacion"
        })
        public static class Sociedad {

            @XmlElement(name = "CDPERSONA", required = true)
            protected String cdpersona;
            @XmlElement(name = "RazonSocial", required = true)
            protected String razonSocial;
            @XmlElement(name = "PaisNacionalidad")
            protected String paisNacionalidad;
            @XmlElement(name = "DocIdentifsPJ", required = true)
            protected Operacion28Y29 .Intervinientes.Sociedad.DocIdentifsPJ docIdentifsPJ;
            @XmlElement(name = "DomiciliosPJ", required = true)
            protected Operacion28Y29 .Intervinientes.Sociedad.DomiciliosPJ domiciliosPJ;
            @XmlElement(name = "Telefonos", required = true)
            protected Operacion28Y29 .Intervinientes.Sociedad.Telefonos telefonos;
            @XmlElement(name = "Relacion")
            protected Integer relacion;

            /**
             * Gets the value of the cdpersona property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCDPERSONA() {
                return cdpersona;
            }

            /**
             * Sets the value of the cdpersona property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCDPERSONA(String value) {
                this.cdpersona = value;
            }

            /**
             * Gets the value of the razonSocial property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRazonSocial() {
                return razonSocial;
            }

            /**
             * Sets the value of the razonSocial property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRazonSocial(String value) {
                this.razonSocial = value;
            }

            /**
             * Gets the value of the paisNacionalidad property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPaisNacionalidad() {
                return paisNacionalidad;
            }

            /**
             * Sets the value of the paisNacionalidad property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPaisNacionalidad(String value) {
                this.paisNacionalidad = value;
            }

            /**
             * Gets the value of the docIdentifsPJ property.
             * 
             * @return
             *     possible object is
             *     {@link Operacion28Y29 .Intervinientes.Sociedad.DocIdentifsPJ }
             *     
             */
            public Operacion28Y29 .Intervinientes.Sociedad.DocIdentifsPJ getDocIdentifsPJ() {
                return docIdentifsPJ;
            }

            /**
             * Sets the value of the docIdentifsPJ property.
             * 
             * @param value
             *     allowed object is
             *     {@link Operacion28Y29 .Intervinientes.Sociedad.DocIdentifsPJ }
             *     
             */
            public void setDocIdentifsPJ(Operacion28Y29 .Intervinientes.Sociedad.DocIdentifsPJ value) {
                this.docIdentifsPJ = value;
            }

            /**
             * Gets the value of the domiciliosPJ property.
             * 
             * @return
             *     possible object is
             *     {@link Operacion28Y29 .Intervinientes.Sociedad.DomiciliosPJ }
             *     
             */
            public Operacion28Y29 .Intervinientes.Sociedad.DomiciliosPJ getDomiciliosPJ() {
                return domiciliosPJ;
            }

            /**
             * Sets the value of the domiciliosPJ property.
             * 
             * @param value
             *     allowed object is
             *     {@link Operacion28Y29 .Intervinientes.Sociedad.DomiciliosPJ }
             *     
             */
            public void setDomiciliosPJ(Operacion28Y29 .Intervinientes.Sociedad.DomiciliosPJ value) {
                this.domiciliosPJ = value;
            }

            /**
             * Gets the value of the telefonos property.
             * 
             * @return
             *     possible object is
             *     {@link Operacion28Y29 .Intervinientes.Sociedad.Telefonos }
             *     
             */
            public Operacion28Y29 .Intervinientes.Sociedad.Telefonos getTelefonos() {
                return telefonos;
            }

            /**
             * Sets the value of the telefonos property.
             * 
             * @param value
             *     allowed object is
             *     {@link Operacion28Y29 .Intervinientes.Sociedad.Telefonos }
             *     
             */
            public void setTelefonos(Operacion28Y29 .Intervinientes.Sociedad.Telefonos value) {
                this.telefonos = value;
            }

            /**
             * Gets the value of the relacion property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRelacion() {
                return relacion;
            }

            /**
             * Sets the value of the relacion property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRelacion(Integer value) {
                this.relacion = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="DocIdentifPJ" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;extension base="{http://www.sepblac.es/DMO}DOCIDENTIF_PJ">
             *               &lt;/extension>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "docIdentifPJ"
            })
            public static class DocIdentifsPJ {

                @XmlElement(name = "DocIdentifPJ")
                protected List<Operacion28Y29 .Intervinientes.Sociedad.DocIdentifsPJ.DocIdentifPJ> docIdentifPJ;

                /**
                 * Gets the value of the docIdentifPJ property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the docIdentifPJ property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getDocIdentifPJ().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Operacion28Y29 .Intervinientes.Sociedad.DocIdentifsPJ.DocIdentifPJ }
                 * 
                 * 
                 */
                public List<Operacion28Y29 .Intervinientes.Sociedad.DocIdentifsPJ.DocIdentifPJ> getDocIdentifPJ() {
                    if (docIdentifPJ == null) {
                        docIdentifPJ = new ArrayList<Operacion28Y29 .Intervinientes.Sociedad.DocIdentifsPJ.DocIdentifPJ>();
                    }
                    return this.docIdentifPJ;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;extension base="{http://www.sepblac.es/DMO}DOCIDENTIF_PJ">
                 *     &lt;/extension>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class DocIdentifPJ
                    extends DOCIDENTIFPJ
                {


                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="DomicilioPJ" type="{http://www.sepblac.es/DMO}DOMICILIO" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "domicilioPJ"
            })
            public static class DomiciliosPJ {

                @XmlElement(name = "DomicilioPJ")
                protected List<DOMICILIO> domicilioPJ;

                /**
                 * Gets the value of the domicilioPJ property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the domicilioPJ property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getDomicilioPJ().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link DOMICILIO }
                 * 
                 * 
                 */
                public List<DOMICILIO> getDomicilioPJ() {
                    if (domicilioPJ == null) {
                        domicilioPJ = new ArrayList<DOMICILIO>();
                    }
                    return this.domicilioPJ;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Telefono" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;extension base="{http://www.sepblac.es/DMO}TELEFONO">
             *               &lt;/extension>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "telefono"
            })
            public static class Telefonos {

                @XmlElement(name = "Telefono")
                protected List<Operacion28Y29 .Intervinientes.Sociedad.Telefonos.Telefono> telefono;

                /**
                 * Gets the value of the telefono property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the telefono property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getTelefono().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Operacion28Y29 .Intervinientes.Sociedad.Telefonos.Telefono }
                 * 
                 * 
                 */
                public List<Operacion28Y29 .Intervinientes.Sociedad.Telefonos.Telefono> getTelefono() {
                    if (telefono == null) {
                        telefono = new ArrayList<Operacion28Y29 .Intervinientes.Sociedad.Telefonos.Telefono>();
                    }
                    return this.telefono;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;extension base="{http://www.sepblac.es/DMO}TELEFONO">
                 *     &lt;/extension>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class Telefono
                    extends TELEFONO
                {


                }

            }

        }

    }

}
