//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.13 at 01:16:38 PM CET 
//


package com.reportingtool.xml.dmo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Persona Fisica genérica
 * 
 * <p>Java class for PERSONAFIS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PERSONAFIS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CDPERSONA">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Nombre" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="80"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrimerApellido" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SegundoApellido" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Pais" type="{http://www.sepblac.es/DMO}PAIS_ENUM" minOccurs="0"/>
 *         &lt;element name="DocIdentifsPF">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DocIdentifPF" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://www.sepblac.es/DMO}DOCIDENTIF_PF">
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DomiciliosPF">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DomicilioPF" type="{http://www.sepblac.es/DMO}DOMICILIO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Telefonos">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Telefono" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://www.sepblac.es/DMO}TELEFONO">
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Relacion" type="{http://www.sepblac.es/DMO}REL_PER_CUENTA_ENUM" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PERSONAFIS", propOrder = {
    "cdpersona",
    "nombre",
    "primerApellido",
    "segundoApellido",
    "pais",
    "docIdentifsPF",
    "domiciliosPF",
    "telefonos",
    "relacion"
})
public class PERSONAFIS {

    @XmlElement(name = "CDPERSONA", required = true)
    protected String cdpersona;
    @XmlElement(name = "Nombre")
    protected String nombre;
    @XmlElement(name = "PrimerApellido")
    protected String primerApellido;
    @XmlElement(name = "SegundoApellido")
    protected String segundoApellido;
    @XmlElement(name = "Pais")
    protected String pais;
    @XmlElement(name = "DocIdentifsPF", required = true)
    protected PERSONAFIS.DocIdentifsPF docIdentifsPF;
    @XmlElement(name = "DomiciliosPF", required = true)
    protected PERSONAFIS.DomiciliosPF domiciliosPF;
    @XmlElement(name = "Telefonos", required = true)
    protected PERSONAFIS.Telefonos telefonos;
    @XmlElement(name = "Relacion")
    protected Integer relacion;

    /**
     * Gets the value of the cdpersona property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCDPERSONA() {
        return cdpersona;
    }

    /**
     * Sets the value of the cdpersona property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCDPERSONA(String value) {
        this.cdpersona = value;
    }

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the primerApellido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimerApellido() {
        return primerApellido;
    }

    /**
     * Sets the value of the primerApellido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimerApellido(String value) {
        this.primerApellido = value;
    }

    /**
     * Gets the value of the segundoApellido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegundoApellido() {
        return segundoApellido;
    }

    /**
     * Sets the value of the segundoApellido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegundoApellido(String value) {
        this.segundoApellido = value;
    }

    /**
     * Gets the value of the pais property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPais() {
        return pais;
    }

    /**
     * Sets the value of the pais property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPais(String value) {
        this.pais = value;
    }

    /**
     * Gets the value of the docIdentifsPF property.
     * 
     * @return
     *     possible object is
     *     {@link PERSONAFIS.DocIdentifsPF }
     *     
     */
    public PERSONAFIS.DocIdentifsPF getDocIdentifsPF() {
        return docIdentifsPF;
    }

    /**
     * Sets the value of the docIdentifsPF property.
     * 
     * @param value
     *     allowed object is
     *     {@link PERSONAFIS.DocIdentifsPF }
     *     
     */
    public void setDocIdentifsPF(PERSONAFIS.DocIdentifsPF value) {
        this.docIdentifsPF = value;
    }

    /**
     * Gets the value of the domiciliosPF property.
     * 
     * @return
     *     possible object is
     *     {@link PERSONAFIS.DomiciliosPF }
     *     
     */
    public PERSONAFIS.DomiciliosPF getDomiciliosPF() {
        return domiciliosPF;
    }

    /**
     * Sets the value of the domiciliosPF property.
     * 
     * @param value
     *     allowed object is
     *     {@link PERSONAFIS.DomiciliosPF }
     *     
     */
    public void setDomiciliosPF(PERSONAFIS.DomiciliosPF value) {
        this.domiciliosPF = value;
    }

    /**
     * Gets the value of the telefonos property.
     * 
     * @return
     *     possible object is
     *     {@link PERSONAFIS.Telefonos }
     *     
     */
    public PERSONAFIS.Telefonos getTelefonos() {
        return telefonos;
    }

    /**
     * Sets the value of the telefonos property.
     * 
     * @param value
     *     allowed object is
     *     {@link PERSONAFIS.Telefonos }
     *     
     */
    public void setTelefonos(PERSONAFIS.Telefonos value) {
        this.telefonos = value;
    }

    /**
     * Gets the value of the relacion property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRelacion() {
        return relacion;
    }

    /**
     * Sets the value of the relacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRelacion(Integer value) {
        this.relacion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DocIdentifPF" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://www.sepblac.es/DMO}DOCIDENTIF_PF">
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "docIdentifPF"
    })
    public static class DocIdentifsPF {

        @XmlElement(name = "DocIdentifPF")
        protected List<PERSONAFIS.DocIdentifsPF.DocIdentifPF> docIdentifPF;

        /**
         * Gets the value of the docIdentifPF property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the docIdentifPF property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDocIdentifPF().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PERSONAFIS.DocIdentifsPF.DocIdentifPF }
         * 
         * 
         */
        public List<PERSONAFIS.DocIdentifsPF.DocIdentifPF> getDocIdentifPF() {
            if (docIdentifPF == null) {
                docIdentifPF = new ArrayList<PERSONAFIS.DocIdentifsPF.DocIdentifPF>();
            }
            return this.docIdentifPF;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://www.sepblac.es/DMO}DOCIDENTIF_PF">
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class DocIdentifPF
            extends DOCIDENTIFPF
        {


        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DomicilioPF" type="{http://www.sepblac.es/DMO}DOMICILIO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "domicilioPF"
    })
    public static class DomiciliosPF {

        @XmlElement(name = "DomicilioPF")
        protected List<DOMICILIO> domicilioPF;

        /**
         * Gets the value of the domicilioPF property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the domicilioPF property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDomicilioPF().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DOMICILIO }
         * 
         * 
         */
        public List<DOMICILIO> getDomicilioPF() {
            if (domicilioPF == null) {
                domicilioPF = new ArrayList<DOMICILIO>();
            }
            return this.domicilioPF;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Telefono" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://www.sepblac.es/DMO}TELEFONO">
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "telefono"
    })
    public static class Telefonos {

        @XmlElement(name = "Telefono")
        protected List<PERSONAFIS.Telefonos.Telefono> telefono;

        /**
         * Gets the value of the telefono property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the telefono property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTelefono().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PERSONAFIS.Telefonos.Telefono }
         * 
         * 
         */
        public List<PERSONAFIS.Telefonos.Telefono> getTelefono() {
            if (telefono == null) {
                telefono = new ArrayList<PERSONAFIS.Telefonos.Telefono>();
            }
            return this.telefono;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://www.sepblac.es/DMO}TELEFONO">
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Telefono
            extends TELEFONO
        {


        }

    }

}
