//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.13 at 01:16:38 PM CET 
//


package com.reportingtool.xml.dmo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="PROVINCIA1" type="{http://www.sepblac.es/DMO}PROV1"/>
 *         &lt;element name="PROVINCIA2" type="{http://www.sepblac.es/DMO}PROV2"/>
 *         &lt;element name="PROVINCIA3" type="{http://www.sepblac.es/DMO}PROV3"/>
 *         &lt;element name="PROVINCIA4" type="{http://www.sepblac.es/DMO}PROV4"/>
 *         &lt;element name="PROVINCIA5" type="{http://www.sepblac.es/DMO}PROV5"/>
 *         &lt;element name="PROVINCIA6" type="{http://www.sepblac.es/DMO}PROV6"/>
 *         &lt;element name="PROVINCIA7" type="{http://www.sepblac.es/DMO}PROV7"/>
 *         &lt;element name="PROVINCIA8" type="{http://www.sepblac.es/DMO}PROV8"/>
 *         &lt;element name="PROVINCIA9" type="{http://www.sepblac.es/DMO}PROV9"/>
 *         &lt;element name="PROVINCIA10" type="{http://www.sepblac.es/DMO}PROV10"/>
 *         &lt;element name="PROVINCIA11" type="{http://www.sepblac.es/DMO}PROV11"/>
 *         &lt;element name="PROVINCIA12" type="{http://www.sepblac.es/DMO}PROV12"/>
 *         &lt;element name="PROVINCIA13" type="{http://www.sepblac.es/DMO}PROV13"/>
 *         &lt;element name="PROVINCIA14" type="{http://www.sepblac.es/DMO}PROV14"/>
 *         &lt;element name="PROVINCIA15" type="{http://www.sepblac.es/DMO}PROV15"/>
 *         &lt;element name="PROVINCIA16" type="{http://www.sepblac.es/DMO}PROV16"/>
 *         &lt;element name="PROVINCIA17" type="{http://www.sepblac.es/DMO}PROV17"/>
 *         &lt;element name="PROVINCIA18" type="{http://www.sepblac.es/DMO}PROV18"/>
 *         &lt;element name="PROVINCIA19" type="{http://www.sepblac.es/DMO}PROV19"/>
 *         &lt;element name="PROVINCIA20" type="{http://www.sepblac.es/DMO}PROV20"/>
 *         &lt;element name="PROVINCIA21" type="{http://www.sepblac.es/DMO}PROV21"/>
 *         &lt;element name="PROVINCIA22" type="{http://www.sepblac.es/DMO}PROV22"/>
 *         &lt;element name="PROVINCIA23" type="{http://www.sepblac.es/DMO}PROV23"/>
 *         &lt;element name="PROVINCIA24" type="{http://www.sepblac.es/DMO}PROV24"/>
 *         &lt;element name="PROVINCIA25" type="{http://www.sepblac.es/DMO}PROV25"/>
 *         &lt;element name="PROVINCIA26" type="{http://www.sepblac.es/DMO}PROV26"/>
 *         &lt;element name="PROVINCIA27" type="{http://www.sepblac.es/DMO}PROV27"/>
 *         &lt;element name="PROVINCIA28" type="{http://www.sepblac.es/DMO}PROV28"/>
 *         &lt;element name="PROVINCIA29" type="{http://www.sepblac.es/DMO}PROV29"/>
 *         &lt;element name="PROVINCIA30" type="{http://www.sepblac.es/DMO}PROV30"/>
 *         &lt;element name="PROVINCIA31" type="{http://www.sepblac.es/DMO}PROV31"/>
 *         &lt;element name="PROVINCIA32" type="{http://www.sepblac.es/DMO}PROV32"/>
 *         &lt;element name="PROVINCIA33" type="{http://www.sepblac.es/DMO}PROV33"/>
 *         &lt;element name="PROVINCIA34" type="{http://www.sepblac.es/DMO}PROV34"/>
 *         &lt;element name="PROVINCIA35" type="{http://www.sepblac.es/DMO}PROV35"/>
 *         &lt;element name="PROVINCIA36" type="{http://www.sepblac.es/DMO}PROV36"/>
 *         &lt;element name="PROVINCIA37" type="{http://www.sepblac.es/DMO}PROV37"/>
 *         &lt;element name="PROVINCIA38" type="{http://www.sepblac.es/DMO}PROV38"/>
 *         &lt;element name="PROVINCIA39" type="{http://www.sepblac.es/DMO}PROV39"/>
 *         &lt;element name="PROVINCIA40" type="{http://www.sepblac.es/DMO}PROV40"/>
 *         &lt;element name="PROVINCIA41" type="{http://www.sepblac.es/DMO}PROV41"/>
 *         &lt;element name="PROVINCIA42" type="{http://www.sepblac.es/DMO}PROV42"/>
 *         &lt;element name="PROVINCIA43" type="{http://www.sepblac.es/DMO}PROV43"/>
 *         &lt;element name="PROVINCIA44" type="{http://www.sepblac.es/DMO}PROV44"/>
 *         &lt;element name="PROVINCIA45" type="{http://www.sepblac.es/DMO}PROV45"/>
 *         &lt;element name="PROVINCIA46" type="{http://www.sepblac.es/DMO}PROV46"/>
 *         &lt;element name="PROVINCIA47" type="{http://www.sepblac.es/DMO}PROV47"/>
 *         &lt;element name="PROVINCIA48" type="{http://www.sepblac.es/DMO}PROV48"/>
 *         &lt;element name="PROVINCIA49" type="{http://www.sepblac.es/DMO}PROV49"/>
 *         &lt;element name="PROVINCIA50" type="{http://www.sepblac.es/DMO}PROV50"/>
 *         &lt;element name="PROVINCIA51" type="{http://www.sepblac.es/DMO}PROV51"/>
 *         &lt;element name="PROVINCIA52" type="{http://www.sepblac.es/DMO}PROV52"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "PROVINCIAS")
public class PROVINCIAS {

    @XmlElement(name = "PROVINCIA1", required = true)
    protected PROV1 provincia1;
    @XmlElement(name = "PROVINCIA2", required = true)
    protected PROV2 provincia2;
    @XmlElement(name = "PROVINCIA3", required = true)
    protected PROV3 provincia3;
    @XmlElement(name = "PROVINCIA4", required = true)
    protected PROV4 provincia4;
    @XmlElement(name = "PROVINCIA5", required = true)
    protected PROV5 provincia5;
    @XmlElement(name = "PROVINCIA6", required = true)
    protected PROV6 provincia6;
    @XmlElement(name = "PROVINCIA7", required = true)
    protected PROV7 provincia7;
    @XmlElement(name = "PROVINCIA8", required = true)
    protected PROV8 provincia8;
    @XmlElement(name = "PROVINCIA9", required = true)
    protected PROV9 provincia9;
    @XmlElement(name = "PROVINCIA10", required = true)
    protected PROV10 provincia10;
    @XmlElement(name = "PROVINCIA11", required = true)
    protected PROV11 provincia11;
    @XmlElement(name = "PROVINCIA12", required = true)
    protected PROV12 provincia12;
    @XmlElement(name = "PROVINCIA13", required = true)
    protected PROV13 provincia13;
    @XmlElement(name = "PROVINCIA14", required = true)
    protected PROV14 provincia14;
    @XmlElement(name = "PROVINCIA15", required = true)
    protected PROV15 provincia15;
    @XmlElement(name = "PROVINCIA16", required = true)
    protected PROV16 provincia16;
    @XmlElement(name = "PROVINCIA17", required = true)
    protected PROV17 provincia17;
    @XmlElement(name = "PROVINCIA18", required = true)
    protected PROV18 provincia18;
    @XmlElement(name = "PROVINCIA19", required = true)
    protected PROV19 provincia19;
    @XmlElement(name = "PROVINCIA20", required = true)
    protected PROV20 provincia20;
    @XmlElement(name = "PROVINCIA21", required = true)
    protected PROV21 provincia21;
    @XmlElement(name = "PROVINCIA22", required = true)
    protected PROV22 provincia22;
    @XmlElement(name = "PROVINCIA23", required = true)
    protected PROV23 provincia23;
    @XmlElement(name = "PROVINCIA24", required = true)
    protected PROV24 provincia24;
    @XmlElement(name = "PROVINCIA25", required = true)
    protected PROV25 provincia25;
    @XmlElement(name = "PROVINCIA26", required = true)
    protected PROV26 provincia26;
    @XmlElement(name = "PROVINCIA27", required = true)
    protected PROV27 provincia27;
    @XmlElement(name = "PROVINCIA28", required = true)
    protected PROV28 provincia28;
    @XmlElement(name = "PROVINCIA29", required = true)
    protected PROV29 provincia29;
    @XmlElement(name = "PROVINCIA30", required = true)
    protected PROV30 provincia30;
    @XmlElement(name = "PROVINCIA31", required = true)
    protected PROV31 provincia31;
    @XmlElement(name = "PROVINCIA32", required = true)
    protected PROV32 provincia32;
    @XmlElement(name = "PROVINCIA33", required = true)
    protected PROV33 provincia33;
    @XmlElement(name = "PROVINCIA34", required = true)
    protected PROV34 provincia34;
    @XmlElement(name = "PROVINCIA35", required = true)
    protected PROV35 provincia35;
    @XmlElement(name = "PROVINCIA36", required = true)
    protected PROV36 provincia36;
    @XmlElement(name = "PROVINCIA37", required = true)
    protected PROV37 provincia37;
    @XmlElement(name = "PROVINCIA38", required = true)
    protected PROV38 provincia38;
    @XmlElement(name = "PROVINCIA39", required = true)
    protected PROV39 provincia39;
    @XmlElement(name = "PROVINCIA40", required = true)
    protected PROV40 provincia40;
    @XmlElement(name = "PROVINCIA41", required = true)
    protected PROV41 provincia41;
    @XmlElement(name = "PROVINCIA42", required = true)
    protected PROV42 provincia42;
    @XmlElement(name = "PROVINCIA43", required = true)
    protected PROV43 provincia43;
    @XmlElement(name = "PROVINCIA44", required = true)
    protected PROV44 provincia44;
    @XmlElement(name = "PROVINCIA45", required = true)
    protected PROV45 provincia45;
    @XmlElement(name = "PROVINCIA46", required = true)
    protected PROV46 provincia46;
    @XmlElement(name = "PROVINCIA47", required = true)
    protected PROV47 provincia47;
    @XmlElement(name = "PROVINCIA48", required = true)
    protected PROV48 provincia48;
    @XmlElement(name = "PROVINCIA49", required = true)
    protected PROV49 provincia49;
    @XmlElement(name = "PROVINCIA50", required = true)
    protected PROV50 provincia50;
    @XmlElement(name = "PROVINCIA51", required = true)
    protected PROV51 provincia51;
    @XmlElement(name = "PROVINCIA52", required = true)
    protected PROV52 provincia52;

    /**
     * Gets the value of the provincia1 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV1 }
     *     
     */
    public PROV1 getPROVINCIA1() {
        return provincia1;
    }

    /**
     * Sets the value of the provincia1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV1 }
     *     
     */
    public void setPROVINCIA1(PROV1 value) {
        this.provincia1 = value;
    }

    /**
     * Gets the value of the provincia2 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV2 }
     *     
     */
    public PROV2 getPROVINCIA2() {
        return provincia2;
    }

    /**
     * Sets the value of the provincia2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV2 }
     *     
     */
    public void setPROVINCIA2(PROV2 value) {
        this.provincia2 = value;
    }

    /**
     * Gets the value of the provincia3 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV3 }
     *     
     */
    public PROV3 getPROVINCIA3() {
        return provincia3;
    }

    /**
     * Sets the value of the provincia3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV3 }
     *     
     */
    public void setPROVINCIA3(PROV3 value) {
        this.provincia3 = value;
    }

    /**
     * Gets the value of the provincia4 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV4 }
     *     
     */
    public PROV4 getPROVINCIA4() {
        return provincia4;
    }

    /**
     * Sets the value of the provincia4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV4 }
     *     
     */
    public void setPROVINCIA4(PROV4 value) {
        this.provincia4 = value;
    }

    /**
     * Gets the value of the provincia5 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV5 }
     *     
     */
    public PROV5 getPROVINCIA5() {
        return provincia5;
    }

    /**
     * Sets the value of the provincia5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV5 }
     *     
     */
    public void setPROVINCIA5(PROV5 value) {
        this.provincia5 = value;
    }

    /**
     * Gets the value of the provincia6 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV6 }
     *     
     */
    public PROV6 getPROVINCIA6() {
        return provincia6;
    }

    /**
     * Sets the value of the provincia6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV6 }
     *     
     */
    public void setPROVINCIA6(PROV6 value) {
        this.provincia6 = value;
    }

    /**
     * Gets the value of the provincia7 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV7 }
     *     
     */
    public PROV7 getPROVINCIA7() {
        return provincia7;
    }

    /**
     * Sets the value of the provincia7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV7 }
     *     
     */
    public void setPROVINCIA7(PROV7 value) {
        this.provincia7 = value;
    }

    /**
     * Gets the value of the provincia8 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV8 }
     *     
     */
    public PROV8 getPROVINCIA8() {
        return provincia8;
    }

    /**
     * Sets the value of the provincia8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV8 }
     *     
     */
    public void setPROVINCIA8(PROV8 value) {
        this.provincia8 = value;
    }

    /**
     * Gets the value of the provincia9 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV9 }
     *     
     */
    public PROV9 getPROVINCIA9() {
        return provincia9;
    }

    /**
     * Sets the value of the provincia9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV9 }
     *     
     */
    public void setPROVINCIA9(PROV9 value) {
        this.provincia9 = value;
    }

    /**
     * Gets the value of the provincia10 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV10 }
     *     
     */
    public PROV10 getPROVINCIA10() {
        return provincia10;
    }

    /**
     * Sets the value of the provincia10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV10 }
     *     
     */
    public void setPROVINCIA10(PROV10 value) {
        this.provincia10 = value;
    }

    /**
     * Gets the value of the provincia11 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV11 }
     *     
     */
    public PROV11 getPROVINCIA11() {
        return provincia11;
    }

    /**
     * Sets the value of the provincia11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV11 }
     *     
     */
    public void setPROVINCIA11(PROV11 value) {
        this.provincia11 = value;
    }

    /**
     * Gets the value of the provincia12 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV12 }
     *     
     */
    public PROV12 getPROVINCIA12() {
        return provincia12;
    }

    /**
     * Sets the value of the provincia12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV12 }
     *     
     */
    public void setPROVINCIA12(PROV12 value) {
        this.provincia12 = value;
    }

    /**
     * Gets the value of the provincia13 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV13 }
     *     
     */
    public PROV13 getPROVINCIA13() {
        return provincia13;
    }

    /**
     * Sets the value of the provincia13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV13 }
     *     
     */
    public void setPROVINCIA13(PROV13 value) {
        this.provincia13 = value;
    }

    /**
     * Gets the value of the provincia14 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV14 }
     *     
     */
    public PROV14 getPROVINCIA14() {
        return provincia14;
    }

    /**
     * Sets the value of the provincia14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV14 }
     *     
     */
    public void setPROVINCIA14(PROV14 value) {
        this.provincia14 = value;
    }

    /**
     * Gets the value of the provincia15 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV15 }
     *     
     */
    public PROV15 getPROVINCIA15() {
        return provincia15;
    }

    /**
     * Sets the value of the provincia15 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV15 }
     *     
     */
    public void setPROVINCIA15(PROV15 value) {
        this.provincia15 = value;
    }

    /**
     * Gets the value of the provincia16 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV16 }
     *     
     */
    public PROV16 getPROVINCIA16() {
        return provincia16;
    }

    /**
     * Sets the value of the provincia16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV16 }
     *     
     */
    public void setPROVINCIA16(PROV16 value) {
        this.provincia16 = value;
    }

    /**
     * Gets the value of the provincia17 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV17 }
     *     
     */
    public PROV17 getPROVINCIA17() {
        return provincia17;
    }

    /**
     * Sets the value of the provincia17 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV17 }
     *     
     */
    public void setPROVINCIA17(PROV17 value) {
        this.provincia17 = value;
    }

    /**
     * Gets the value of the provincia18 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV18 }
     *     
     */
    public PROV18 getPROVINCIA18() {
        return provincia18;
    }

    /**
     * Sets the value of the provincia18 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV18 }
     *     
     */
    public void setPROVINCIA18(PROV18 value) {
        this.provincia18 = value;
    }

    /**
     * Gets the value of the provincia19 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV19 }
     *     
     */
    public PROV19 getPROVINCIA19() {
        return provincia19;
    }

    /**
     * Sets the value of the provincia19 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV19 }
     *     
     */
    public void setPROVINCIA19(PROV19 value) {
        this.provincia19 = value;
    }

    /**
     * Gets the value of the provincia20 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV20 }
     *     
     */
    public PROV20 getPROVINCIA20() {
        return provincia20;
    }

    /**
     * Sets the value of the provincia20 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV20 }
     *     
     */
    public void setPROVINCIA20(PROV20 value) {
        this.provincia20 = value;
    }

    /**
     * Gets the value of the provincia21 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV21 }
     *     
     */
    public PROV21 getPROVINCIA21() {
        return provincia21;
    }

    /**
     * Sets the value of the provincia21 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV21 }
     *     
     */
    public void setPROVINCIA21(PROV21 value) {
        this.provincia21 = value;
    }

    /**
     * Gets the value of the provincia22 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV22 }
     *     
     */
    public PROV22 getPROVINCIA22() {
        return provincia22;
    }

    /**
     * Sets the value of the provincia22 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV22 }
     *     
     */
    public void setPROVINCIA22(PROV22 value) {
        this.provincia22 = value;
    }

    /**
     * Gets the value of the provincia23 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV23 }
     *     
     */
    public PROV23 getPROVINCIA23() {
        return provincia23;
    }

    /**
     * Sets the value of the provincia23 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV23 }
     *     
     */
    public void setPROVINCIA23(PROV23 value) {
        this.provincia23 = value;
    }

    /**
     * Gets the value of the provincia24 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV24 }
     *     
     */
    public PROV24 getPROVINCIA24() {
        return provincia24;
    }

    /**
     * Sets the value of the provincia24 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV24 }
     *     
     */
    public void setPROVINCIA24(PROV24 value) {
        this.provincia24 = value;
    }

    /**
     * Gets the value of the provincia25 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV25 }
     *     
     */
    public PROV25 getPROVINCIA25() {
        return provincia25;
    }

    /**
     * Sets the value of the provincia25 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV25 }
     *     
     */
    public void setPROVINCIA25(PROV25 value) {
        this.provincia25 = value;
    }

    /**
     * Gets the value of the provincia26 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV26 }
     *     
     */
    public PROV26 getPROVINCIA26() {
        return provincia26;
    }

    /**
     * Sets the value of the provincia26 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV26 }
     *     
     */
    public void setPROVINCIA26(PROV26 value) {
        this.provincia26 = value;
    }

    /**
     * Gets the value of the provincia27 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV27 }
     *     
     */
    public PROV27 getPROVINCIA27() {
        return provincia27;
    }

    /**
     * Sets the value of the provincia27 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV27 }
     *     
     */
    public void setPROVINCIA27(PROV27 value) {
        this.provincia27 = value;
    }

    /**
     * Gets the value of the provincia28 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV28 }
     *     
     */
    public PROV28 getPROVINCIA28() {
        return provincia28;
    }

    /**
     * Sets the value of the provincia28 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV28 }
     *     
     */
    public void setPROVINCIA28(PROV28 value) {
        this.provincia28 = value;
    }

    /**
     * Gets the value of the provincia29 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV29 }
     *     
     */
    public PROV29 getPROVINCIA29() {
        return provincia29;
    }

    /**
     * Sets the value of the provincia29 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV29 }
     *     
     */
    public void setPROVINCIA29(PROV29 value) {
        this.provincia29 = value;
    }

    /**
     * Gets the value of the provincia30 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV30 }
     *     
     */
    public PROV30 getPROVINCIA30() {
        return provincia30;
    }

    /**
     * Sets the value of the provincia30 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV30 }
     *     
     */
    public void setPROVINCIA30(PROV30 value) {
        this.provincia30 = value;
    }

    /**
     * Gets the value of the provincia31 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV31 }
     *     
     */
    public PROV31 getPROVINCIA31() {
        return provincia31;
    }

    /**
     * Sets the value of the provincia31 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV31 }
     *     
     */
    public void setPROVINCIA31(PROV31 value) {
        this.provincia31 = value;
    }

    /**
     * Gets the value of the provincia32 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV32 }
     *     
     */
    public PROV32 getPROVINCIA32() {
        return provincia32;
    }

    /**
     * Sets the value of the provincia32 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV32 }
     *     
     */
    public void setPROVINCIA32(PROV32 value) {
        this.provincia32 = value;
    }

    /**
     * Gets the value of the provincia33 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV33 }
     *     
     */
    public PROV33 getPROVINCIA33() {
        return provincia33;
    }

    /**
     * Sets the value of the provincia33 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV33 }
     *     
     */
    public void setPROVINCIA33(PROV33 value) {
        this.provincia33 = value;
    }

    /**
     * Gets the value of the provincia34 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV34 }
     *     
     */
    public PROV34 getPROVINCIA34() {
        return provincia34;
    }

    /**
     * Sets the value of the provincia34 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV34 }
     *     
     */
    public void setPROVINCIA34(PROV34 value) {
        this.provincia34 = value;
    }

    /**
     * Gets the value of the provincia35 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV35 }
     *     
     */
    public PROV35 getPROVINCIA35() {
        return provincia35;
    }

    /**
     * Sets the value of the provincia35 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV35 }
     *     
     */
    public void setPROVINCIA35(PROV35 value) {
        this.provincia35 = value;
    }

    /**
     * Gets the value of the provincia36 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV36 }
     *     
     */
    public PROV36 getPROVINCIA36() {
        return provincia36;
    }

    /**
     * Sets the value of the provincia36 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV36 }
     *     
     */
    public void setPROVINCIA36(PROV36 value) {
        this.provincia36 = value;
    }

    /**
     * Gets the value of the provincia37 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV37 }
     *     
     */
    public PROV37 getPROVINCIA37() {
        return provincia37;
    }

    /**
     * Sets the value of the provincia37 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV37 }
     *     
     */
    public void setPROVINCIA37(PROV37 value) {
        this.provincia37 = value;
    }

    /**
     * Gets the value of the provincia38 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV38 }
     *     
     */
    public PROV38 getPROVINCIA38() {
        return provincia38;
    }

    /**
     * Sets the value of the provincia38 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV38 }
     *     
     */
    public void setPROVINCIA38(PROV38 value) {
        this.provincia38 = value;
    }

    /**
     * Gets the value of the provincia39 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV39 }
     *     
     */
    public PROV39 getPROVINCIA39() {
        return provincia39;
    }

    /**
     * Sets the value of the provincia39 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV39 }
     *     
     */
    public void setPROVINCIA39(PROV39 value) {
        this.provincia39 = value;
    }

    /**
     * Gets the value of the provincia40 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV40 }
     *     
     */
    public PROV40 getPROVINCIA40() {
        return provincia40;
    }

    /**
     * Sets the value of the provincia40 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV40 }
     *     
     */
    public void setPROVINCIA40(PROV40 value) {
        this.provincia40 = value;
    }

    /**
     * Gets the value of the provincia41 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV41 }
     *     
     */
    public PROV41 getPROVINCIA41() {
        return provincia41;
    }

    /**
     * Sets the value of the provincia41 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV41 }
     *     
     */
    public void setPROVINCIA41(PROV41 value) {
        this.provincia41 = value;
    }

    /**
     * Gets the value of the provincia42 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV42 }
     *     
     */
    public PROV42 getPROVINCIA42() {
        return provincia42;
    }

    /**
     * Sets the value of the provincia42 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV42 }
     *     
     */
    public void setPROVINCIA42(PROV42 value) {
        this.provincia42 = value;
    }

    /**
     * Gets the value of the provincia43 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV43 }
     *     
     */
    public PROV43 getPROVINCIA43() {
        return provincia43;
    }

    /**
     * Sets the value of the provincia43 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV43 }
     *     
     */
    public void setPROVINCIA43(PROV43 value) {
        this.provincia43 = value;
    }

    /**
     * Gets the value of the provincia44 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV44 }
     *     
     */
    public PROV44 getPROVINCIA44() {
        return provincia44;
    }

    /**
     * Sets the value of the provincia44 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV44 }
     *     
     */
    public void setPROVINCIA44(PROV44 value) {
        this.provincia44 = value;
    }

    /**
     * Gets the value of the provincia45 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV45 }
     *     
     */
    public PROV45 getPROVINCIA45() {
        return provincia45;
    }

    /**
     * Sets the value of the provincia45 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV45 }
     *     
     */
    public void setPROVINCIA45(PROV45 value) {
        this.provincia45 = value;
    }

    /**
     * Gets the value of the provincia46 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV46 }
     *     
     */
    public PROV46 getPROVINCIA46() {
        return provincia46;
    }

    /**
     * Sets the value of the provincia46 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV46 }
     *     
     */
    public void setPROVINCIA46(PROV46 value) {
        this.provincia46 = value;
    }

    /**
     * Gets the value of the provincia47 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV47 }
     *     
     */
    public PROV47 getPROVINCIA47() {
        return provincia47;
    }

    /**
     * Sets the value of the provincia47 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV47 }
     *     
     */
    public void setPROVINCIA47(PROV47 value) {
        this.provincia47 = value;
    }

    /**
     * Gets the value of the provincia48 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV48 }
     *     
     */
    public PROV48 getPROVINCIA48() {
        return provincia48;
    }

    /**
     * Sets the value of the provincia48 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV48 }
     *     
     */
    public void setPROVINCIA48(PROV48 value) {
        this.provincia48 = value;
    }

    /**
     * Gets the value of the provincia49 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV49 }
     *     
     */
    public PROV49 getPROVINCIA49() {
        return provincia49;
    }

    /**
     * Sets the value of the provincia49 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV49 }
     *     
     */
    public void setPROVINCIA49(PROV49 value) {
        this.provincia49 = value;
    }

    /**
     * Gets the value of the provincia50 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV50 }
     *     
     */
    public PROV50 getPROVINCIA50() {
        return provincia50;
    }

    /**
     * Sets the value of the provincia50 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV50 }
     *     
     */
    public void setPROVINCIA50(PROV50 value) {
        this.provincia50 = value;
    }

    /**
     * Gets the value of the provincia51 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV51 }
     *     
     */
    public PROV51 getPROVINCIA51() {
        return provincia51;
    }

    /**
     * Sets the value of the provincia51 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV51 }
     *     
     */
    public void setPROVINCIA51(PROV51 value) {
        this.provincia51 = value;
    }

    /**
     * Gets the value of the provincia52 property.
     * 
     * @return
     *     possible object is
     *     {@link PROV52 }
     *     
     */
    public PROV52 getPROVINCIA52() {
        return provincia52;
    }

    /**
     * Sets the value of the provincia52 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROV52 }
     *     
     */
    public void setPROVINCIA52(PROV52 value) {
        this.provincia52 = value;
    }

}
