//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.13 at 01:16:38 PM CET 
//


package com.reportingtool.xml.dmo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TIPODECL_ENUM.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TIPODECL_ENUM">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Positiva"/>
 *     &lt;enumeration value="Negativa"/>
 *     &lt;enumeration value="Movimiento"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TIPODECL_ENUM")
@XmlEnum
public enum TIPODECLENUM {

    @XmlEnumValue("Positiva")
    POSITIVA("Positiva"),
    @XmlEnumValue("Negativa")
    NEGATIVA("Negativa"),
    @XmlEnumValue("Movimiento")
    MOVIMIENTO("Movimiento");
    private final String value;

    TIPODECLENUM(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TIPODECLENUM fromValue(String v) {
        for (TIPODECLENUM c: TIPODECLENUM.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
