 -- ORACLE EXTENDED
 
 CREATE TABLE "REPORTING"."T_ROLE" 
   (	"ROLENAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	 PRIMARY KEY ("ROLENAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REPORTING"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REPORTING" ;
 
  CREATE TABLE "REPORTING"."T_USER" 
   (	"USERNAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ENABLED" NUMBER(1,0) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"LAST_LOGIN_TMS" TIMESTAMP (6), 
	"LAST_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(255 CHAR), 
	"COMPANY_ID" NUMBER(19,0), 
	 PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REPORTING"  ENABLE, 
	 CONSTRAINT "FK_USER_COMPANY" FOREIGN KEY ("COMPANY_ID")
	  REFERENCES "REPORTING"."T_COMPANY" ("COMPANY_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REPORTING" ;
 
CREATE TABLE "REPORTING"."T_USER_ROLE" 
   (	"ROLENAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "FK_QHG4VHMIDO9407WNPI9VKU0QA" FOREIGN KEY ("USERNAME")
	  REFERENCES "REPORTING"."T_USER" ("USERNAME") ENABLE, 
	 CONSTRAINT "FK_TO3UN7OQ2MG7J0ME2PCJQ7FBD" FOREIGN KEY ("ROLENAME")
	  REFERENCES "REPORTING"."T_ROLE" ("ROLENAME") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REPORTING" ;
 
 -- OR ORACLE
 
CREATE TABLE "REPORTING"."T_ROLE" 
   (	"ROLENAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	 PRIMARY KEY ("ROLENAME")
   ) 
;

  CREATE TABLE "REPORTING"."T_COMPANY" 
   (	"COMPANY_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"COMPANY_CODE" VARCHAR2(40 CHAR), 
	"COMPANY_COUNTRY" VARCHAR2(255 CHAR), 
	"COMPANY_DESC" VARCHAR2(255 CHAR), 
	"COMPANY_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"VERSION" NUMBER(10,0) NOT NULL ENABLE, 
	"CREATE_TMS" TIMESTAMP (6) NOT NULL ENABLE, 
	"CREATE_ID" VARCHAR2(128 CHAR) NOT NULL ENABLE, 
	"IS_DELETED" NUMBER(1,0) NOT NULL ENABLE, 
	"REF_ID" NUMBER(19,0), 
	 PRIMARY KEY ("COMPANY_ID")
   ) ;
 
  CREATE TABLE "REPORTING"."T_USER" 
   (	"USERNAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ENABLED" NUMBER(1,0) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"LAST_LOGIN_TMS" TIMESTAMP (6), 
	"LAST_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(255 CHAR), 
	"COMPANY_ID" NUMBER(19,0), 
	PRIMARY KEY ("USERNAME"),
	CONSTRAINT "FK_USER_COMPANY" FOREIGN KEY ("COMPANY_ID")
	REFERENCES "REPORTING"."T_COMPANY" ("COMPANY_ID") ENABLE
   );
 
CREATE TABLE "REPORTING"."T_USER_ROLE" 
   (	"ROLENAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "FK_QHG4VHMIDO9407WNPI9VKU0QA" FOREIGN KEY ("USERNAME")
	  REFERENCES "REPORTING"."T_USER" ("USERNAME") ENABLE, 
	 CONSTRAINT "FK_TO3UN7OQ2MG7J0ME2PCJQ7FBD" FOREIGN KEY ("ROLENAME")
	  REFERENCES "REPORTING"."T_ROLE" ("ROLENAME") ENABLE
   ) 
;


-- OR MYSQL

CREATE TABLE REPORTING.T_ROLE
   (	ROLENAME VARCHAR(255) NOT NULL, 
	 PRIMARY KEY (ROLENAME)
   ) 
;

  CREATE TABLE REPORTING.T_USER 
   (	USERNAME VARCHAR(255 ) NOT NULL , 
	ENABLED BOOLEAN NOT NULL , 
	FIRST_NAME VARCHAR(255 ) NOT NULL , 
	LAST_LOGIN_TMS TIMESTAMP , 
	LAST_NAME VARCHAR(255 ) NOT NULL , 
	PASSWORD VARCHAR(255 ) NOT NULL , 
	EMAIL VARCHAR(255 ), 
	COMPANY_ID BIGINT, 
	PRIMARY KEY (USERNAME)
   );
   
   --CONSTRAINT FK_USER_COMPANY FOREIGN KEY (COMPANY_ID)
	--REFERENCES REPORTING.T_COMPANY (COMPANY_ID) 
	
	CREATE TABLE REPORTING.T_USER_ROLE 
   (	ROLENAME VARCHAR(255) NOT NULL, 
	USERNAME VARCHAR(255) NOT NULL, 
	 CONSTRAINT FK_QHG4VHMIDO9407WNPI9VKU0QA FOREIGN KEY (USERNAME)
	  REFERENCES REPORTING.T_USER (USERNAME), 
	 CONSTRAINT FK_TO3UN7OQ2MG7J0ME2PCJQ7FBD FOREIGN KEY (ROLENAME)
	  REFERENCES REPORTING.T_ROLE (ROLENAME)
   ) 
   
     CREATE TABLE REPORTING.T_COMPANY 
   (	COMPANY_ID BIGINT NOT NULL , 
	COMPANY_CODE VARCHAR(40 ), 
	COMPANY_COUNTRY VARCHAR(255 ), 
	COMPANY_DESC VARCHAR(255 ), 
	COMPANY_NAME VARCHAR(255 ) NOT NULL , 
	VERSION BIGINT NOT NULL , 
	CREATE_TMS TIMESTAMP  NOT NULL , 
	CREATE_ID VARCHAR(128 ) NOT NULL , 
	IS_DELETED BOOLEAN NOT NULL , 
	REF_ID BIGINT, 
	 PRIMARY KEY (COMPANY_ID)
   ) ;
;


-- INSERTS ORACLE


Insert into T_ROLE (ROLENAME) values ('ROLE_ADMIN');
Insert into T_ROLE (ROLENAME) values ('ROLE_USER');

--Insert into T_USER (USERNAME,ENABLED,FIRST_NAME,LAST_LOGIN_TMS,LAST_NAME,PASSWORD,EMAIL) 
--values ('user','1','userName',sysdate,'userLastName','3d517fe6ebab7b8cfcf98db6259c8a59','user@company.com'); -- user0
Insert into T_USER (USERNAME,ENABLED,FIRST_NAME,LAST_LOGIN_TMS,LAST_NAME,PASSWORD,EMAIL) 
values ('admin','1','adminName',sysdate,'adminLastName','62f04a011fbb80030bb0a13701c20b41','admin-reporting@riskms.com'); -- admin0

--Insert into T_USER_ROLE (ROLENAME,USERNAME) values ('ROLE_USER','user');
Insert into T_USER_ROLE (ROLENAME,USERNAME) values ('ROLE_ADMIN','admin');
Insert into T_USER_ROLE (ROLENAME,USERNAME) values ('ROLE_USER','admin');


-- INSERTS MYSQL
use reporting;

Insert into T_ROLE (ROLENAME) values ('ROLE_ADMIN');
Insert into T_ROLE (ROLENAME) values ('ROLE_USER');

--Insert into T_USER (USERNAME,ENABLED,FIRST_NAME,LAST_LOGIN_TMS,LAST_NAME,PASSWORD,EMAIL) 
--values ('user',true,'userName',sysdate(),'userLastName','3d517fe6ebab7b8cfcf98db6259c8a59','user@company.com'); -- user0
Insert into T_USER (USERNAME,ENABLED,FIRST_NAME,LAST_LOGIN_TMS,LAST_NAME,PASSWORD,EMAIL) 
values ('admin',true,'adminName',sysdate(),'adminLastName','62f04a011fbb80030bb0a13701c20b41','admin-reporting@riskms.com'); -- admin0

--Insert into T_USER_ROLE (ROLENAME,USERNAME) values ('ROLE_USER','user');
Insert into T_USER_ROLE (ROLENAME,USERNAME) values ('ROLE_ADMIN','admin');
Insert into T_USER_ROLE (ROLENAME,USERNAME) values ('ROLE_USER','admin');

